import { useNavigate } from 'react-router-dom';
import { useTwoStepVerification } from './useTwoStepVerification';
import TwoStepVerificationView from './TwoStepVerificationView';

const TwoStepVerificationPage = () => {
  const navigate = useNavigate();
  const state = useTwoStepVerification();

  return (
    <div className="min-h-screen flex items-center justify-center bg-gray-50 p-6 font-sans">
      <div className="w-full max-w-md bg-white rounded-[2.5rem] shadow-2xl shadow-gray-200/50 p-10 lg:p-12 border border-gray-50 text-center">
        
        <div className="w-16 h-16 bg-yellow-50 rounded-2xl flex items-center justify-center mx-auto mb-8">
            <span className="text-2xl animate-pulse">🔒</span>
        </div>

        <header className="mb-10">
          <h1 className="text-3xl font-black text-gray-900 uppercase tracking-tight">
            Security <span className="text-yellow-500">Check</span>
          </h1>
          <p className="mt-4 text-gray-400 text-sm font-medium leading-relaxed">
            Please enter the authentication code generated by your device to continue.
          </p>
        </header>

        <TwoStepVerificationView
          code={state.code}
          error={state.error}
          loading={state.loading}
          onCodeChange={state.updateCode}
          onSubmit={state.submit}
          onReset={state.reset}
          onBack={() => navigate('/login')}
        />

        <div className="mt-12 flex flex-col gap-4">
            <div className="h-[1px] bg-gray-50 w-full"></div>
            <p className="text-[9px] text-gray-300 font-black uppercase tracking-[0.4em]">
                Protected by EntrioX Security
            </p>
        </div>
      </div>
    </div>
  );
};

export default TwoStepVerificationPage;