// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repository;

#nullable disable

namespace EntrioX.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20251224193821_AddLoyaltyPointsToUser")]
    partial class AddLoyaltyPointsToUser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UserId");

                    b.Property<string>("BankAccountNumber")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<int>("LoyaltyPoints")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("AppUsers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            BankAccountNumber = "BA392004000012345678",
                            Email = "emin@example.com",
                            FullName = "Emin Džanko",
                            LoyaltyPoints = 0
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            Email = "john.smith@example.com",
                            FullName = "John Smith",
                            LoyaltyPoints = 0
                        });
                });

            modelBuilder.Entity("Entities.Models.Reward", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("RewardId");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("GrantedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Rewards");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Description = "Early supporter reward",
                            GrantedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "/images/rewards/supporter.png",
                            UserId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa")
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Description = "Top buyer of the month",
                            GrantedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "/images/rewards/topbuyer.png",
                            UserId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb")
                        });
                });

            modelBuilder.Entity("Entities.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Event", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("EventId");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("EventDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("MinTicketPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e1000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2025, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A night of indie rock excellence in the heart of Sarajevo.",
                            EventDate = new DateTime(2026, 6, 15, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationId = new Guid("f1000000-0000-0000-0000-000000000001"),
                            MinTicketPrice = 0m,
                            Name = "Arctic Monkeys World Tour"
                        },
                        new
                        {
                            Id = new Guid("e2000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2025, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Join the biggest regional gathering of IT experts and innovators.",
                            EventDate = new DateTime(2026, 9, 20, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationId = new Guid("f2000000-0000-0000-0000-000000000002"),
                            MinTicketPrice = 0m,
                            Name = "Tech Conference 2026"
                        },
                        new
                        {
                            Id = new Guid("e3000000-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2025, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A classic festive performance by the Sarajevo Philharmonic Orchestra.",
                            EventDate = new DateTime(2026, 12, 24, 19, 30, 0, 0, DateTimeKind.Unspecified),
                            LocationId = new Guid("f3000000-0000-0000-0000-000000000003"),
                            MinTicketPrice = 0m,
                            Name = "The Nutcracker Ballet"
                        });
                });

            modelBuilder.Entity("Location", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("LocationId");

                    b.Property<string>("Address")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double?>("GeoLatitude")
                        .HasColumnType("float");

                    b.Property<double?>("GeoLongitude")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Locations");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f1000000-0000-0000-0000-000000000001"),
                            Address = "Alipašina bb, Sarajevo",
                            GeoLatitude = 43.866199999999999,
                            GeoLongitude = 18.4131,
                            Name = "Zetra Olympic Hall"
                        },
                        new
                        {
                            Id = new Guid("f2000000-0000-0000-0000-000000000002"),
                            Address = "Terezija bb, Sarajevo",
                            GeoLatitude = 43.856400000000001,
                            GeoLongitude = 18.413,
                            Name = "Skenderija Plateau"
                        },
                        new
                        {
                            Id = new Guid("f3000000-0000-0000-0000-000000000003"),
                            Address = "Obala Kulina bana 9",
                            GeoLatitude = 43.857500000000002,
                            GeoLongitude = 18.4206,
                            Name = "National Theater Sarajevo"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Reservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ReservationId");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("TotalPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("UserId");

                    b.ToTable("Reservations");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d1000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EventId = new Guid("e1000000-0000-0000-0000-000000000001"),
                            TotalPrice = 50.00m,
                            UserId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa")
                        });
                });

            modelBuilder.Entity("Ticket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("TicketId");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsReserved")
                        .HasColumnType("bit");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("QRCode")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid?>("ReservationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SeatNumber")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("ReservationId");

                    b.ToTable("Tickets");

                    b.HasData(
                        new
                        {
                            Id = new Guid("eb4a4861-b64a-4556-ad11-af539e99f3fe"),
                            EventId = new Guid("e1000000-0000-0000-0000-000000000001"),
                            IsReserved = false,
                            Price = 55.00m,
                            SeatNumber = "A1"
                        },
                        new
                        {
                            Id = new Guid("eb341118-fad1-4727-a462-300be0ba2eb7"),
                            EventId = new Guid("e1000000-0000-0000-0000-000000000001"),
                            IsReserved = false,
                            Price = 55.00m,
                            SeatNumber = "A2"
                        },
                        new
                        {
                            Id = new Guid("6448e453-ecc6-4a12-afbc-8ee6207bddcb"),
                            EventId = new Guid("e1000000-0000-0000-0000-000000000001"),
                            IsReserved = false,
                            Price = 55.00m,
                            SeatNumber = "A3"
                        },
                        new
                        {
                            Id = new Guid("96627c2a-b16b-4b3b-a006-fe1a393eac05"),
                            EventId = new Guid("e1000000-0000-0000-0000-000000000001"),
                            IsReserved = false,
                            Price = 55.00m,
                            SeatNumber = "A4"
                        },
                        new
                        {
                            Id = new Guid("776352fb-4cf4-4c2c-902b-55fa29003c93"),
                            EventId = new Guid("e1000000-0000-0000-0000-000000000001"),
                            IsReserved = false,
                            Price = 55.00m,
                            SeatNumber = "A5"
                        },
                        new
                        {
                            Id = new Guid("9d40f54d-e7ea-4244-9e9f-f772d2efea81"),
                            EventId = new Guid("e1000000-0000-0000-0000-000000000001"),
                            IsReserved = false,
                            Price = 55.00m,
                            SeatNumber = "A6"
                        },
                        new
                        {
                            Id = new Guid("b8900bd5-60ec-4c0f-9a27-4c6975df3493"),
                            EventId = new Guid("e1000000-0000-0000-0000-000000000001"),
                            IsReserved = false,
                            Price = 55.00m,
                            SeatNumber = "A7"
                        },
                        new
                        {
                            Id = new Guid("1e48e263-29a1-4b3d-aec9-cc201b02527e"),
                            EventId = new Guid("e1000000-0000-0000-0000-000000000001"),
                            IsReserved = false,
                            Price = 55.00m,
                            SeatNumber = "A8"
                        },
                        new
                        {
                            Id = new Guid("6e0e2ffa-397c-4261-bfdd-865f6b04eb46"),
                            EventId = new Guid("e1000000-0000-0000-0000-000000000001"),
                            IsReserved = false,
                            Price = 55.00m,
                            SeatNumber = "A9"
                        },
                        new
                        {
                            Id = new Guid("349dacc7-68d4-4b0b-8ccf-f7930502ff63"),
                            EventId = new Guid("e1000000-0000-0000-0000-000000000001"),
                            IsReserved = false,
                            Price = 55.00m,
                            SeatNumber = "A10"
                        },
                        new
                        {
                            Id = new Guid("ac3532d6-0b9b-4760-9cf8-cc240c2f29c6"),
                            EventId = new Guid("e1000000-0000-0000-0000-000000000001"),
                            IsReserved = false,
                            Price = 55.00m,
                            SeatNumber = "B1"
                        },
                        new
                        {
                            Id = new Guid("438628a3-72c7-49f7-94fd-3f698a5ed9af"),
                            EventId = new Guid("e1000000-0000-0000-0000-000000000001"),
                            IsReserved = false,
                            Price = 55.00m,
                            SeatNumber = "B2"
                        },
                        new
                        {
                            Id = new Guid("844f60b3-ea5e-49d5-bbdd-2d3d353a44e4"),
                            EventId = new Guid("e1000000-0000-0000-0000-000000000001"),
                            IsReserved = false,
                            Price = 55.00m,
                            SeatNumber = "B3"
                        },
                        new
                        {
                            Id = new Guid("fa8e2071-5856-443b-bb36-e299ed76d503"),
                            EventId = new Guid("e1000000-0000-0000-0000-000000000001"),
                            IsReserved = false,
                            Price = 55.00m,
                            SeatNumber = "B4"
                        },
                        new
                        {
                            Id = new Guid("744caf82-28a4-4006-b4ce-00d20d8a18dd"),
                            EventId = new Guid("e1000000-0000-0000-0000-000000000001"),
                            IsReserved = false,
                            Price = 55.00m,
                            SeatNumber = "B5"
                        },
                        new
                        {
                            Id = new Guid("fc0c8a58-3037-48b5-ba65-a877ffd15642"),
                            EventId = new Guid("e1000000-0000-0000-0000-000000000001"),
                            IsReserved = false,
                            Price = 55.00m,
                            SeatNumber = "B6"
                        },
                        new
                        {
                            Id = new Guid("0b041736-7f90-450d-a778-70eff2c16732"),
                            EventId = new Guid("e1000000-0000-0000-0000-000000000001"),
                            IsReserved = false,
                            Price = 55.00m,
                            SeatNumber = "B7"
                        },
                        new
                        {
                            Id = new Guid("15bfd245-173f-4adf-b70b-d5cabb0d5f10"),
                            EventId = new Guid("e1000000-0000-0000-0000-000000000001"),
                            IsReserved = false,
                            Price = 55.00m,
                            SeatNumber = "B8"
                        },
                        new
                        {
                            Id = new Guid("c774ca00-78ce-4e2b-939e-62f6e4611873"),
                            EventId = new Guid("e1000000-0000-0000-0000-000000000001"),
                            IsReserved = false,
                            Price = 55.00m,
                            SeatNumber = "B9"
                        },
                        new
                        {
                            Id = new Guid("17ca035b-e5bd-42c0-ba6c-e985317cb1c5"),
                            EventId = new Guid("e1000000-0000-0000-0000-000000000001"),
                            IsReserved = false,
                            Price = 55.00m,
                            SeatNumber = "B10"
                        },
                        new
                        {
                            Id = new Guid("c7655963-8fef-473f-be76-7787cd588ee7"),
                            EventId = new Guid("e1000000-0000-0000-0000-000000000001"),
                            IsReserved = false,
                            Price = 55.00m,
                            SeatNumber = "C1"
                        },
                        new
                        {
                            Id = new Guid("cce3eec7-4539-44eb-ad18-637b0a4a0619"),
                            EventId = new Guid("e1000000-0000-0000-0000-000000000001"),
                            IsReserved = false,
                            Price = 55.00m,
                            SeatNumber = "C2"
                        },
                        new
                        {
                            Id = new Guid("87a9baf6-4549-488e-bf1f-045a3f18044f"),
                            EventId = new Guid("e1000000-0000-0000-0000-000000000001"),
                            IsReserved = false,
                            Price = 55.00m,
                            SeatNumber = "C3"
                        },
                        new
                        {
                            Id = new Guid("2f2428c6-c988-4167-b460-2763b52148f9"),
                            EventId = new Guid("e1000000-0000-0000-0000-000000000001"),
                            IsReserved = false,
                            Price = 55.00m,
                            SeatNumber = "C4"
                        },
                        new
                        {
                            Id = new Guid("f16712b9-e00e-4024-aff3-7fd22fa33630"),
                            EventId = new Guid("e1000000-0000-0000-0000-000000000001"),
                            IsReserved = false,
                            Price = 55.00m,
                            SeatNumber = "C5"
                        },
                        new
                        {
                            Id = new Guid("5db8972b-279a-4a01-b643-740e00e7ba9f"),
                            EventId = new Guid("e1000000-0000-0000-0000-000000000001"),
                            IsReserved = false,
                            Price = 55.00m,
                            SeatNumber = "C6"
                        },
                        new
                        {
                            Id = new Guid("b514aff4-8b1e-47cc-b28a-4a9ca279bb1e"),
                            EventId = new Guid("e1000000-0000-0000-0000-000000000001"),
                            IsReserved = false,
                            Price = 55.00m,
                            SeatNumber = "C7"
                        },
                        new
                        {
                            Id = new Guid("264e7831-6bf0-4330-a6c6-b6f538601787"),
                            EventId = new Guid("e1000000-0000-0000-0000-000000000001"),
                            IsReserved = false,
                            Price = 55.00m,
                            SeatNumber = "C8"
                        },
                        new
                        {
                            Id = new Guid("fddc94f2-509b-4e2c-852d-9a38153d6f8e"),
                            EventId = new Guid("e1000000-0000-0000-0000-000000000001"),
                            IsReserved = false,
                            Price = 55.00m,
                            SeatNumber = "C9"
                        },
                        new
                        {
                            Id = new Guid("96665bdb-e366-4bc7-b985-8c249f052f61"),
                            EventId = new Guid("e1000000-0000-0000-0000-000000000001"),
                            IsReserved = false,
                            Price = 55.00m,
                            SeatNumber = "C10"
                        },
                        new
                        {
                            Id = new Guid("cb793598-b514-400d-bafc-9d28aa8cd94c"),
                            EventId = new Guid("e2000000-0000-0000-0000-000000000002"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "A1"
                        },
                        new
                        {
                            Id = new Guid("895af36f-8830-4e51-8c98-2f5a891f56bf"),
                            EventId = new Guid("e2000000-0000-0000-0000-000000000002"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "A2"
                        },
                        new
                        {
                            Id = new Guid("58ba71d2-b7eb-43b8-bc9d-6a9c20694be0"),
                            EventId = new Guid("e2000000-0000-0000-0000-000000000002"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "A3"
                        },
                        new
                        {
                            Id = new Guid("5d81282e-9b8f-40f4-b052-8a4cf9e78a14"),
                            EventId = new Guid("e2000000-0000-0000-0000-000000000002"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "A4"
                        },
                        new
                        {
                            Id = new Guid("011bd3c4-591e-4dcd-934c-71efea0ad56f"),
                            EventId = new Guid("e2000000-0000-0000-0000-000000000002"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "A5"
                        },
                        new
                        {
                            Id = new Guid("f3a211f4-31a7-4edd-b472-113f91560126"),
                            EventId = new Guid("e2000000-0000-0000-0000-000000000002"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "A6"
                        },
                        new
                        {
                            Id = new Guid("913082e6-739b-40a6-9db6-4c4781b1a504"),
                            EventId = new Guid("e2000000-0000-0000-0000-000000000002"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "A7"
                        },
                        new
                        {
                            Id = new Guid("a96fe51d-6290-4e69-bac0-8a21821c5d0b"),
                            EventId = new Guid("e2000000-0000-0000-0000-000000000002"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "A8"
                        },
                        new
                        {
                            Id = new Guid("ae20cfb1-3baf-4bc7-8de2-295cbaf735d4"),
                            EventId = new Guid("e2000000-0000-0000-0000-000000000002"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "A9"
                        },
                        new
                        {
                            Id = new Guid("9f55314f-9d5f-4856-921d-0410d8c9b7b6"),
                            EventId = new Guid("e2000000-0000-0000-0000-000000000002"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "A10"
                        },
                        new
                        {
                            Id = new Guid("1912d443-9420-4eba-ac38-02212c53a4f1"),
                            EventId = new Guid("e2000000-0000-0000-0000-000000000002"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "B1"
                        },
                        new
                        {
                            Id = new Guid("0f76a71f-82a5-4ab5-b0ed-6a0be2e5ba0f"),
                            EventId = new Guid("e2000000-0000-0000-0000-000000000002"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "B2"
                        },
                        new
                        {
                            Id = new Guid("95eb5ffa-972e-4b6e-88b2-512f75382659"),
                            EventId = new Guid("e2000000-0000-0000-0000-000000000002"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "B3"
                        },
                        new
                        {
                            Id = new Guid("af54385f-52e2-4726-8b56-bd86870bb0b1"),
                            EventId = new Guid("e2000000-0000-0000-0000-000000000002"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "B4"
                        },
                        new
                        {
                            Id = new Guid("f0298a9f-95a4-4463-ad4d-0ccc434a6252"),
                            EventId = new Guid("e2000000-0000-0000-0000-000000000002"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "B5"
                        },
                        new
                        {
                            Id = new Guid("2547f485-04a2-45bc-8b7a-4ce4faa24cb9"),
                            EventId = new Guid("e2000000-0000-0000-0000-000000000002"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "B6"
                        },
                        new
                        {
                            Id = new Guid("0a110820-c310-4f5b-91b4-f5607e3ace84"),
                            EventId = new Guid("e2000000-0000-0000-0000-000000000002"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "B7"
                        },
                        new
                        {
                            Id = new Guid("8f46d261-ba85-4f3d-a2b4-7a1db1fa50cf"),
                            EventId = new Guid("e2000000-0000-0000-0000-000000000002"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "B8"
                        },
                        new
                        {
                            Id = new Guid("8a6f4935-be56-4aaa-9976-28c8bc4d5824"),
                            EventId = new Guid("e2000000-0000-0000-0000-000000000002"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "B9"
                        },
                        new
                        {
                            Id = new Guid("7a652bfe-efbb-4e79-974a-720e8de0f88b"),
                            EventId = new Guid("e2000000-0000-0000-0000-000000000002"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "B10"
                        },
                        new
                        {
                            Id = new Guid("3b29634e-0832-4a9c-a9d6-bbcc17dcffbd"),
                            EventId = new Guid("e2000000-0000-0000-0000-000000000002"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "C1"
                        },
                        new
                        {
                            Id = new Guid("f1567ad1-ad8e-47e2-a921-073a8987592d"),
                            EventId = new Guid("e2000000-0000-0000-0000-000000000002"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "C2"
                        },
                        new
                        {
                            Id = new Guid("711260fc-1ae8-4137-a4d8-27eda59cb0e1"),
                            EventId = new Guid("e2000000-0000-0000-0000-000000000002"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "C3"
                        },
                        new
                        {
                            Id = new Guid("8d0bc035-8af2-4a6e-b859-b549a75d6880"),
                            EventId = new Guid("e2000000-0000-0000-0000-000000000002"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "C4"
                        },
                        new
                        {
                            Id = new Guid("b422175a-71dc-4a1f-b4a0-792a395cc4b1"),
                            EventId = new Guid("e2000000-0000-0000-0000-000000000002"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "C5"
                        },
                        new
                        {
                            Id = new Guid("6f995d22-5acd-4fd9-bb15-f43883fbf849"),
                            EventId = new Guid("e2000000-0000-0000-0000-000000000002"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "C6"
                        },
                        new
                        {
                            Id = new Guid("805d0e76-2c8a-47d5-a1c2-784b92b6d50f"),
                            EventId = new Guid("e2000000-0000-0000-0000-000000000002"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "C7"
                        },
                        new
                        {
                            Id = new Guid("7be6e4fa-4f87-45d7-9332-f3ef241da32c"),
                            EventId = new Guid("e2000000-0000-0000-0000-000000000002"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "C8"
                        },
                        new
                        {
                            Id = new Guid("24c27063-6da7-412f-aeb3-7349a4b88a42"),
                            EventId = new Guid("e2000000-0000-0000-0000-000000000002"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "C9"
                        },
                        new
                        {
                            Id = new Guid("70034bb4-a75b-47ec-9230-6b51c769ab7f"),
                            EventId = new Guid("e2000000-0000-0000-0000-000000000002"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "C10"
                        },
                        new
                        {
                            Id = new Guid("81c4885f-52f9-488c-bb7e-0c3490d3daf1"),
                            EventId = new Guid("e3000000-0000-0000-0000-000000000003"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "A1"
                        },
                        new
                        {
                            Id = new Guid("484cf31f-1c8f-4e69-9080-0b351a673cc3"),
                            EventId = new Guid("e3000000-0000-0000-0000-000000000003"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "A2"
                        },
                        new
                        {
                            Id = new Guid("cc3cc54e-e14e-49a9-a3e8-39025dc8f33f"),
                            EventId = new Guid("e3000000-0000-0000-0000-000000000003"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "A3"
                        },
                        new
                        {
                            Id = new Guid("f6f02178-944f-4f64-99f5-ee09859f1ebe"),
                            EventId = new Guid("e3000000-0000-0000-0000-000000000003"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "A4"
                        },
                        new
                        {
                            Id = new Guid("c1b84fbe-ba7b-4fed-9b64-f22ce8e064ad"),
                            EventId = new Guid("e3000000-0000-0000-0000-000000000003"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "A5"
                        },
                        new
                        {
                            Id = new Guid("7124765c-8f78-4cb9-8584-30e6decea8c5"),
                            EventId = new Guid("e3000000-0000-0000-0000-000000000003"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "A6"
                        },
                        new
                        {
                            Id = new Guid("1b0c5a7f-6c12-43e0-af7d-c7cb67c28a45"),
                            EventId = new Guid("e3000000-0000-0000-0000-000000000003"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "A7"
                        },
                        new
                        {
                            Id = new Guid("1f21ade6-c9f9-45f8-9596-b4971da97a80"),
                            EventId = new Guid("e3000000-0000-0000-0000-000000000003"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "A8"
                        },
                        new
                        {
                            Id = new Guid("bc3822e8-44b1-4772-b75d-daddff3030bc"),
                            EventId = new Guid("e3000000-0000-0000-0000-000000000003"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "A9"
                        },
                        new
                        {
                            Id = new Guid("9e269aae-97c7-49ac-a36e-cf5b99e4e50e"),
                            EventId = new Guid("e3000000-0000-0000-0000-000000000003"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "A10"
                        },
                        new
                        {
                            Id = new Guid("77c5ef75-06fb-40c8-93f2-204eaf2505bb"),
                            EventId = new Guid("e3000000-0000-0000-0000-000000000003"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "B1"
                        },
                        new
                        {
                            Id = new Guid("612a2b4e-5af3-4a75-b557-178bdb1c7669"),
                            EventId = new Guid("e3000000-0000-0000-0000-000000000003"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "B2"
                        },
                        new
                        {
                            Id = new Guid("ebbb9178-dd07-40c2-bb5b-fa4d64152942"),
                            EventId = new Guid("e3000000-0000-0000-0000-000000000003"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "B3"
                        },
                        new
                        {
                            Id = new Guid("ee70a2b1-799b-43da-a033-48a65424e7c7"),
                            EventId = new Guid("e3000000-0000-0000-0000-000000000003"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "B4"
                        },
                        new
                        {
                            Id = new Guid("8aad8efe-d45b-4027-9d23-ffd016c674a1"),
                            EventId = new Guid("e3000000-0000-0000-0000-000000000003"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "B5"
                        },
                        new
                        {
                            Id = new Guid("7f6719bf-7248-42f0-80bc-e425f50b7c2d"),
                            EventId = new Guid("e3000000-0000-0000-0000-000000000003"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "B6"
                        },
                        new
                        {
                            Id = new Guid("8693c6ee-f386-47df-b0c3-684d90210483"),
                            EventId = new Guid("e3000000-0000-0000-0000-000000000003"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "B7"
                        },
                        new
                        {
                            Id = new Guid("568c88fb-1962-4236-9510-2dcd80408cb1"),
                            EventId = new Guid("e3000000-0000-0000-0000-000000000003"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "B8"
                        },
                        new
                        {
                            Id = new Guid("35033291-ccb7-4722-9549-ac05b18dda74"),
                            EventId = new Guid("e3000000-0000-0000-0000-000000000003"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "B9"
                        },
                        new
                        {
                            Id = new Guid("19c96e40-d672-4c49-83ee-b2f0d01309ee"),
                            EventId = new Guid("e3000000-0000-0000-0000-000000000003"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "B10"
                        },
                        new
                        {
                            Id = new Guid("f8a008f7-ebef-40ad-83d2-f488f04bdcb7"),
                            EventId = new Guid("e3000000-0000-0000-0000-000000000003"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "C1"
                        },
                        new
                        {
                            Id = new Guid("1798b49a-b856-415f-b7d4-4eab47d90df4"),
                            EventId = new Guid("e3000000-0000-0000-0000-000000000003"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "C2"
                        },
                        new
                        {
                            Id = new Guid("96f88326-0c8b-4629-b75a-8259bf6548f3"),
                            EventId = new Guid("e3000000-0000-0000-0000-000000000003"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "C3"
                        },
                        new
                        {
                            Id = new Guid("814fea6f-0f13-4bcb-a0fb-d8ecb22ff319"),
                            EventId = new Guid("e3000000-0000-0000-0000-000000000003"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "C4"
                        },
                        new
                        {
                            Id = new Guid("a3d01be8-5ccc-423a-887d-bc61edd4a9e4"),
                            EventId = new Guid("e3000000-0000-0000-0000-000000000003"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "C5"
                        },
                        new
                        {
                            Id = new Guid("dc4a60e8-21a1-49a8-9b3c-dfcd8c17128a"),
                            EventId = new Guid("e3000000-0000-0000-0000-000000000003"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "C6"
                        },
                        new
                        {
                            Id = new Guid("b32657c6-9f7d-4ba4-9bc0-ea4507eabca6"),
                            EventId = new Guid("e3000000-0000-0000-0000-000000000003"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "C7"
                        },
                        new
                        {
                            Id = new Guid("ce2f70a5-820d-4d57-8f08-fe0c62e9a176"),
                            EventId = new Guid("e3000000-0000-0000-0000-000000000003"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "C8"
                        },
                        new
                        {
                            Id = new Guid("226cd088-388b-4be1-a851-b723d84c0289"),
                            EventId = new Guid("e3000000-0000-0000-0000-000000000003"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "C9"
                        },
                        new
                        {
                            Id = new Guid("58bfc56c-b2d4-4189-b64e-edd2a7b32420"),
                            EventId = new Guid("e3000000-0000-0000-0000-000000000003"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "C10"
                        });
                });

            modelBuilder.Entity("Entities.Models.Reward", b =>
                {
                    b.HasOne("AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Event", b =>
                {
                    b.HasOne("Location", "Location")
                        .WithMany("Events")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Entities.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Entities.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Entities.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Reservation", b =>
                {
                    b.HasOne("Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppUser", "User")
                        .WithMany("Reservations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Ticket", b =>
                {
                    b.HasOne("Event", "Event")
                        .WithMany("Tickets")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Reservation", "Reservation")
                        .WithMany("Tickets")
                        .HasForeignKey("ReservationId");

                    b.Navigation("Event");

                    b.Navigation("Reservation");
                });

            modelBuilder.Entity("AppUser", b =>
                {
                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("Event", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("Location", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("Reservation", b =>
                {
                    b.Navigation("Tickets");
                });
#pragma warning restore 612, 618
        }
    }
}
