// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repository;

#nullable disable

namespace EntrioX.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20251223210557_SeedEnglishDataFinal")]
    partial class SeedEnglishDataFinal
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UserId");

                    b.Property<string>("BankAccountNumber")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.ToTable("AppUsers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            BankAccountNumber = "BA392004000012345678",
                            Email = "emin@example.com",
                            FullName = "Emin Džanko"
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            Email = "john.smith@example.com",
                            FullName = "John Smith"
                        });
                });

            modelBuilder.Entity("Entities.Models.Reward", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("RewardId");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("GrantedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Rewards");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Description = "Early supporter reward",
                            GrantedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "/images/rewards/supporter.png",
                            UserId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa")
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Description = "Top buyer of the month",
                            GrantedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "/images/rewards/topbuyer.png",
                            UserId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb")
                        });
                });

            modelBuilder.Entity("Entities.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Event", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("EventId");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("EventDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("MinTicketPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e1000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2025, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A night of indie rock excellence in the heart of Sarajevo.",
                            EventDate = new DateTime(2026, 6, 15, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationId = new Guid("f1000000-0000-0000-0000-000000000001"),
                            MinTicketPrice = 0m,
                            Name = "Arctic Monkeys World Tour"
                        },
                        new
                        {
                            Id = new Guid("e2000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2025, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Join the biggest regional gathering of IT experts and innovators.",
                            EventDate = new DateTime(2026, 9, 20, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationId = new Guid("f2000000-0000-0000-0000-000000000002"),
                            MinTicketPrice = 0m,
                            Name = "Tech Conference 2026"
                        },
                        new
                        {
                            Id = new Guid("e3000000-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2025, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A classic festive performance by the Sarajevo Philharmonic Orchestra.",
                            EventDate = new DateTime(2026, 12, 24, 19, 30, 0, 0, DateTimeKind.Unspecified),
                            LocationId = new Guid("f3000000-0000-0000-0000-000000000003"),
                            MinTicketPrice = 0m,
                            Name = "The Nutcracker Ballet"
                        });
                });

            modelBuilder.Entity("Location", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("LocationId");

                    b.Property<string>("Address")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double?>("GeoLatitude")
                        .HasColumnType("float");

                    b.Property<double?>("GeoLongitude")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Locations");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f1000000-0000-0000-0000-000000000001"),
                            Address = "Alipašina bb, Sarajevo",
                            GeoLatitude = 43.866199999999999,
                            GeoLongitude = 18.4131,
                            Name = "Zetra Olympic Hall"
                        },
                        new
                        {
                            Id = new Guid("f2000000-0000-0000-0000-000000000002"),
                            Address = "Terezija bb, Sarajevo",
                            GeoLatitude = 43.856400000000001,
                            GeoLongitude = 18.413,
                            Name = "Skenderija Plateau"
                        },
                        new
                        {
                            Id = new Guid("f3000000-0000-0000-0000-000000000003"),
                            Address = "Obala Kulina bana 9",
                            GeoLatitude = 43.857500000000002,
                            GeoLongitude = 18.4206,
                            Name = "National Theater Sarajevo"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Reservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ReservationId");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("TotalPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("UserId");

                    b.ToTable("Reservations");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d1000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EventId = new Guid("e1000000-0000-0000-0000-000000000001"),
                            TotalPrice = 50.00m,
                            UserId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa")
                        });
                });

            modelBuilder.Entity("Ticket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("TicketId");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsReserved")
                        .HasColumnType("bit");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("QRCode")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid?>("ReservationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SeatNumber")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("ReservationId");

                    b.ToTable("Tickets");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d166f5ef-83b7-443a-8c5c-2228f73e6656"),
                            EventId = new Guid("e1000000-0000-0000-0000-000000000001"),
                            IsReserved = false,
                            Price = 55.00m,
                            SeatNumber = "A1"
                        },
                        new
                        {
                            Id = new Guid("d497495e-3d52-4088-81fd-98052cff73aa"),
                            EventId = new Guid("e1000000-0000-0000-0000-000000000001"),
                            IsReserved = false,
                            Price = 55.00m,
                            SeatNumber = "A2"
                        },
                        new
                        {
                            Id = new Guid("22b51d38-ce58-421a-90e3-c9f8834e36a6"),
                            EventId = new Guid("e1000000-0000-0000-0000-000000000001"),
                            IsReserved = false,
                            Price = 55.00m,
                            SeatNumber = "A3"
                        },
                        new
                        {
                            Id = new Guid("bed2ee63-9033-4d41-acea-e14fd9774179"),
                            EventId = new Guid("e1000000-0000-0000-0000-000000000001"),
                            IsReserved = false,
                            Price = 55.00m,
                            SeatNumber = "A4"
                        },
                        new
                        {
                            Id = new Guid("9b2e8bac-4197-46a8-a22f-31567261cb7e"),
                            EventId = new Guid("e1000000-0000-0000-0000-000000000001"),
                            IsReserved = false,
                            Price = 55.00m,
                            SeatNumber = "A5"
                        },
                        new
                        {
                            Id = new Guid("e1555f68-cec1-4ec8-8598-da0932ec59d1"),
                            EventId = new Guid("e1000000-0000-0000-0000-000000000001"),
                            IsReserved = false,
                            Price = 55.00m,
                            SeatNumber = "A6"
                        },
                        new
                        {
                            Id = new Guid("e1522355-bc2b-4662-9027-65633b4cefcb"),
                            EventId = new Guid("e1000000-0000-0000-0000-000000000001"),
                            IsReserved = false,
                            Price = 55.00m,
                            SeatNumber = "A7"
                        },
                        new
                        {
                            Id = new Guid("9b2dbc8d-f355-4624-ac38-7996cb35d0cf"),
                            EventId = new Guid("e1000000-0000-0000-0000-000000000001"),
                            IsReserved = false,
                            Price = 55.00m,
                            SeatNumber = "A8"
                        },
                        new
                        {
                            Id = new Guid("c9044f91-dac8-40ff-92f7-1c7871ce69ef"),
                            EventId = new Guid("e1000000-0000-0000-0000-000000000001"),
                            IsReserved = false,
                            Price = 55.00m,
                            SeatNumber = "A9"
                        },
                        new
                        {
                            Id = new Guid("f9442e13-e535-471c-9fd3-b7f7f7fa9be8"),
                            EventId = new Guid("e1000000-0000-0000-0000-000000000001"),
                            IsReserved = false,
                            Price = 55.00m,
                            SeatNumber = "A10"
                        },
                        new
                        {
                            Id = new Guid("3dfcbce9-727b-441b-b15f-0959e7b30832"),
                            EventId = new Guid("e1000000-0000-0000-0000-000000000001"),
                            IsReserved = false,
                            Price = 55.00m,
                            SeatNumber = "B1"
                        },
                        new
                        {
                            Id = new Guid("0982763e-eaa0-48ea-8d5b-a54bb95ece6a"),
                            EventId = new Guid("e1000000-0000-0000-0000-000000000001"),
                            IsReserved = false,
                            Price = 55.00m,
                            SeatNumber = "B2"
                        },
                        new
                        {
                            Id = new Guid("07e82bb3-de33-4a7f-90ff-fe0d265aa3f1"),
                            EventId = new Guid("e1000000-0000-0000-0000-000000000001"),
                            IsReserved = false,
                            Price = 55.00m,
                            SeatNumber = "B3"
                        },
                        new
                        {
                            Id = new Guid("388f71d0-92b1-41dc-8c00-ec4d93940b4e"),
                            EventId = new Guid("e1000000-0000-0000-0000-000000000001"),
                            IsReserved = false,
                            Price = 55.00m,
                            SeatNumber = "B4"
                        },
                        new
                        {
                            Id = new Guid("186632c5-c443-4f7c-bfdd-e5f3bfd0b889"),
                            EventId = new Guid("e1000000-0000-0000-0000-000000000001"),
                            IsReserved = false,
                            Price = 55.00m,
                            SeatNumber = "B5"
                        },
                        new
                        {
                            Id = new Guid("4e7ab616-9f15-4786-b496-fc7135350c4a"),
                            EventId = new Guid("e1000000-0000-0000-0000-000000000001"),
                            IsReserved = false,
                            Price = 55.00m,
                            SeatNumber = "B6"
                        },
                        new
                        {
                            Id = new Guid("ed8f7b1e-5136-42f1-8d5f-f001150cb7bc"),
                            EventId = new Guid("e1000000-0000-0000-0000-000000000001"),
                            IsReserved = false,
                            Price = 55.00m,
                            SeatNumber = "B7"
                        },
                        new
                        {
                            Id = new Guid("1800956b-3908-49bd-b0de-6a23a5815ba5"),
                            EventId = new Guid("e1000000-0000-0000-0000-000000000001"),
                            IsReserved = false,
                            Price = 55.00m,
                            SeatNumber = "B8"
                        },
                        new
                        {
                            Id = new Guid("5b38663c-f211-4770-9b30-e2c2a5aa9bde"),
                            EventId = new Guid("e1000000-0000-0000-0000-000000000001"),
                            IsReserved = false,
                            Price = 55.00m,
                            SeatNumber = "B9"
                        },
                        new
                        {
                            Id = new Guid("6a596e8e-3472-4f85-b1b5-abfd92f6999c"),
                            EventId = new Guid("e1000000-0000-0000-0000-000000000001"),
                            IsReserved = false,
                            Price = 55.00m,
                            SeatNumber = "B10"
                        },
                        new
                        {
                            Id = new Guid("a8e5490f-ecee-4682-a2d6-a3768109aeea"),
                            EventId = new Guid("e1000000-0000-0000-0000-000000000001"),
                            IsReserved = false,
                            Price = 55.00m,
                            SeatNumber = "C1"
                        },
                        new
                        {
                            Id = new Guid("58c99d14-6de4-4ff8-9b37-a660d9149a62"),
                            EventId = new Guid("e1000000-0000-0000-0000-000000000001"),
                            IsReserved = false,
                            Price = 55.00m,
                            SeatNumber = "C2"
                        },
                        new
                        {
                            Id = new Guid("7e5cd2eb-87d5-4a2f-bdef-5f4fa1fb1e57"),
                            EventId = new Guid("e1000000-0000-0000-0000-000000000001"),
                            IsReserved = false,
                            Price = 55.00m,
                            SeatNumber = "C3"
                        },
                        new
                        {
                            Id = new Guid("01e01205-b8ed-40cf-a24a-6ba91b59664d"),
                            EventId = new Guid("e1000000-0000-0000-0000-000000000001"),
                            IsReserved = false,
                            Price = 55.00m,
                            SeatNumber = "C4"
                        },
                        new
                        {
                            Id = new Guid("b0ba42da-b23d-47cb-8023-e7f764bbc3b9"),
                            EventId = new Guid("e1000000-0000-0000-0000-000000000001"),
                            IsReserved = false,
                            Price = 55.00m,
                            SeatNumber = "C5"
                        },
                        new
                        {
                            Id = new Guid("575081dd-9f3e-442f-a967-bacbf66c692c"),
                            EventId = new Guid("e1000000-0000-0000-0000-000000000001"),
                            IsReserved = false,
                            Price = 55.00m,
                            SeatNumber = "C6"
                        },
                        new
                        {
                            Id = new Guid("f4776e2a-4c73-4474-ac42-df273db5d36c"),
                            EventId = new Guid("e1000000-0000-0000-0000-000000000001"),
                            IsReserved = false,
                            Price = 55.00m,
                            SeatNumber = "C7"
                        },
                        new
                        {
                            Id = new Guid("1f186440-facb-4243-abd4-e8aa1764f681"),
                            EventId = new Guid("e1000000-0000-0000-0000-000000000001"),
                            IsReserved = false,
                            Price = 55.00m,
                            SeatNumber = "C8"
                        },
                        new
                        {
                            Id = new Guid("df1249ca-2cee-4ab7-b4fb-f5bae5fb33ff"),
                            EventId = new Guid("e1000000-0000-0000-0000-000000000001"),
                            IsReserved = false,
                            Price = 55.00m,
                            SeatNumber = "C9"
                        },
                        new
                        {
                            Id = new Guid("ffdacf0c-652d-4847-8520-54dae95beb4c"),
                            EventId = new Guid("e1000000-0000-0000-0000-000000000001"),
                            IsReserved = false,
                            Price = 55.00m,
                            SeatNumber = "C10"
                        },
                        new
                        {
                            Id = new Guid("16dd56df-4665-4722-9e95-29709cc22913"),
                            EventId = new Guid("e2000000-0000-0000-0000-000000000002"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "A1"
                        },
                        new
                        {
                            Id = new Guid("8ad16916-1d88-4251-a5a0-e52b8724f2d7"),
                            EventId = new Guid("e2000000-0000-0000-0000-000000000002"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "A2"
                        },
                        new
                        {
                            Id = new Guid("1e079a04-2c11-4a81-9db6-461e1379253b"),
                            EventId = new Guid("e2000000-0000-0000-0000-000000000002"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "A3"
                        },
                        new
                        {
                            Id = new Guid("5c995eab-ff4b-4aa9-bf38-30c5801f5cb0"),
                            EventId = new Guid("e2000000-0000-0000-0000-000000000002"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "A4"
                        },
                        new
                        {
                            Id = new Guid("e49e8126-5d76-4832-bbcb-64851a0b881e"),
                            EventId = new Guid("e2000000-0000-0000-0000-000000000002"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "A5"
                        },
                        new
                        {
                            Id = new Guid("bc3fea09-048c-4baf-9e8b-a52b32bef2f8"),
                            EventId = new Guid("e2000000-0000-0000-0000-000000000002"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "A6"
                        },
                        new
                        {
                            Id = new Guid("ebdb1d84-6201-4706-88ba-0a59e1818591"),
                            EventId = new Guid("e2000000-0000-0000-0000-000000000002"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "A7"
                        },
                        new
                        {
                            Id = new Guid("b033cd3a-0866-41df-9bf0-a2619545a18c"),
                            EventId = new Guid("e2000000-0000-0000-0000-000000000002"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "A8"
                        },
                        new
                        {
                            Id = new Guid("2532b03f-61be-49d4-bd5f-e532298e39db"),
                            EventId = new Guid("e2000000-0000-0000-0000-000000000002"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "A9"
                        },
                        new
                        {
                            Id = new Guid("694bbfe3-fecc-4630-9735-0ea803055b38"),
                            EventId = new Guid("e2000000-0000-0000-0000-000000000002"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "A10"
                        },
                        new
                        {
                            Id = new Guid("65ca8154-e630-4197-9ad4-89998e25a46a"),
                            EventId = new Guid("e2000000-0000-0000-0000-000000000002"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "B1"
                        },
                        new
                        {
                            Id = new Guid("eee8c118-fd60-4aa3-86a8-be35e38fda3c"),
                            EventId = new Guid("e2000000-0000-0000-0000-000000000002"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "B2"
                        },
                        new
                        {
                            Id = new Guid("08addd3d-2186-4ed9-8b5f-5f0564f300fe"),
                            EventId = new Guid("e2000000-0000-0000-0000-000000000002"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "B3"
                        },
                        new
                        {
                            Id = new Guid("16952442-cce5-4b39-9a47-e02ce008a16f"),
                            EventId = new Guid("e2000000-0000-0000-0000-000000000002"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "B4"
                        },
                        new
                        {
                            Id = new Guid("c3064b26-2622-4b25-a27e-ed828318ccab"),
                            EventId = new Guid("e2000000-0000-0000-0000-000000000002"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "B5"
                        },
                        new
                        {
                            Id = new Guid("16696c06-a53e-486b-acb9-8bcb084788ea"),
                            EventId = new Guid("e2000000-0000-0000-0000-000000000002"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "B6"
                        },
                        new
                        {
                            Id = new Guid("011a224c-8d3e-4791-b6ae-0e4d6f7cbe0d"),
                            EventId = new Guid("e2000000-0000-0000-0000-000000000002"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "B7"
                        },
                        new
                        {
                            Id = new Guid("8c137f41-9a39-4003-ace4-c68883c03853"),
                            EventId = new Guid("e2000000-0000-0000-0000-000000000002"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "B8"
                        },
                        new
                        {
                            Id = new Guid("106aa9a9-287d-4e36-b6cb-32c893340758"),
                            EventId = new Guid("e2000000-0000-0000-0000-000000000002"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "B9"
                        },
                        new
                        {
                            Id = new Guid("4560ccf0-b05b-4f57-8fa8-d0a7912b6990"),
                            EventId = new Guid("e2000000-0000-0000-0000-000000000002"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "B10"
                        },
                        new
                        {
                            Id = new Guid("73ccc9b3-7e45-45ad-b90b-623224a0e5be"),
                            EventId = new Guid("e2000000-0000-0000-0000-000000000002"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "C1"
                        },
                        new
                        {
                            Id = new Guid("0ac31926-c5f1-4eba-b770-142905fd9a64"),
                            EventId = new Guid("e2000000-0000-0000-0000-000000000002"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "C2"
                        },
                        new
                        {
                            Id = new Guid("7e4e4460-beb5-4575-8ebd-8845afa4a80a"),
                            EventId = new Guid("e2000000-0000-0000-0000-000000000002"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "C3"
                        },
                        new
                        {
                            Id = new Guid("215e7836-5b36-49c1-9f15-220a572abe46"),
                            EventId = new Guid("e2000000-0000-0000-0000-000000000002"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "C4"
                        },
                        new
                        {
                            Id = new Guid("bf9c45a7-d33e-4843-b81a-13642b0b7e4e"),
                            EventId = new Guid("e2000000-0000-0000-0000-000000000002"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "C5"
                        },
                        new
                        {
                            Id = new Guid("31e9c4e6-5e5f-4f01-85e9-e13a9bf7c410"),
                            EventId = new Guid("e2000000-0000-0000-0000-000000000002"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "C6"
                        },
                        new
                        {
                            Id = new Guid("dd8a5a3e-381f-430f-bcf4-f1fc304611b2"),
                            EventId = new Guid("e2000000-0000-0000-0000-000000000002"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "C7"
                        },
                        new
                        {
                            Id = new Guid("6d54e014-9423-47d2-9463-2ee3f60f4c74"),
                            EventId = new Guid("e2000000-0000-0000-0000-000000000002"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "C8"
                        },
                        new
                        {
                            Id = new Guid("0ccafe58-68bc-49eb-8bc4-734b179afb0a"),
                            EventId = new Guid("e2000000-0000-0000-0000-000000000002"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "C9"
                        },
                        new
                        {
                            Id = new Guid("95298126-7a85-4067-96c2-2770f3fbcf04"),
                            EventId = new Guid("e2000000-0000-0000-0000-000000000002"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "C10"
                        },
                        new
                        {
                            Id = new Guid("05ec9826-c181-4e25-bf9b-36b89169e0a0"),
                            EventId = new Guid("e3000000-0000-0000-0000-000000000003"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "A1"
                        },
                        new
                        {
                            Id = new Guid("effab696-ba24-46fb-924e-c7200568cb74"),
                            EventId = new Guid("e3000000-0000-0000-0000-000000000003"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "A2"
                        },
                        new
                        {
                            Id = new Guid("426a6e7a-0355-412a-8afc-1eaea1701ccf"),
                            EventId = new Guid("e3000000-0000-0000-0000-000000000003"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "A3"
                        },
                        new
                        {
                            Id = new Guid("742bebde-0a16-40a8-9fce-6c5f85feec43"),
                            EventId = new Guid("e3000000-0000-0000-0000-000000000003"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "A4"
                        },
                        new
                        {
                            Id = new Guid("b859cdae-6dff-46e1-a473-92e97cafcaa3"),
                            EventId = new Guid("e3000000-0000-0000-0000-000000000003"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "A5"
                        },
                        new
                        {
                            Id = new Guid("1bf0866e-2137-454b-a75e-1b747e3c11e5"),
                            EventId = new Guid("e3000000-0000-0000-0000-000000000003"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "A6"
                        },
                        new
                        {
                            Id = new Guid("61950c0c-cbe1-418c-84fb-5f8f6bc6f39e"),
                            EventId = new Guid("e3000000-0000-0000-0000-000000000003"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "A7"
                        },
                        new
                        {
                            Id = new Guid("48011230-57a3-405a-b36d-3ec5054277b7"),
                            EventId = new Guid("e3000000-0000-0000-0000-000000000003"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "A8"
                        },
                        new
                        {
                            Id = new Guid("a2b5c58a-ed07-4f8a-a3cb-344ef90790a6"),
                            EventId = new Guid("e3000000-0000-0000-0000-000000000003"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "A9"
                        },
                        new
                        {
                            Id = new Guid("8925e19a-44ea-4f51-8ba3-12c4f0559387"),
                            EventId = new Guid("e3000000-0000-0000-0000-000000000003"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "A10"
                        },
                        new
                        {
                            Id = new Guid("deb55de5-8baf-4e8d-8470-acb3d36121a0"),
                            EventId = new Guid("e3000000-0000-0000-0000-000000000003"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "B1"
                        },
                        new
                        {
                            Id = new Guid("df3717cc-a64b-4d97-9c77-4ccb21fb817d"),
                            EventId = new Guid("e3000000-0000-0000-0000-000000000003"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "B2"
                        },
                        new
                        {
                            Id = new Guid("c18318c2-7fcf-4646-86d7-77c715321e74"),
                            EventId = new Guid("e3000000-0000-0000-0000-000000000003"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "B3"
                        },
                        new
                        {
                            Id = new Guid("60ef739e-31a4-443b-be5d-f2b5baf82900"),
                            EventId = new Guid("e3000000-0000-0000-0000-000000000003"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "B4"
                        },
                        new
                        {
                            Id = new Guid("8d5f9408-f5ab-40b5-a191-f70fa937b8d2"),
                            EventId = new Guid("e3000000-0000-0000-0000-000000000003"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "B5"
                        },
                        new
                        {
                            Id = new Guid("1244a71a-dcdf-448a-a0be-7842205543cf"),
                            EventId = new Guid("e3000000-0000-0000-0000-000000000003"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "B6"
                        },
                        new
                        {
                            Id = new Guid("441e4a21-df70-4ec2-b973-7667ad88dc1c"),
                            EventId = new Guid("e3000000-0000-0000-0000-000000000003"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "B7"
                        },
                        new
                        {
                            Id = new Guid("899cc353-4087-4b29-92e8-4fcfa9e8b868"),
                            EventId = new Guid("e3000000-0000-0000-0000-000000000003"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "B8"
                        },
                        new
                        {
                            Id = new Guid("85c9f0ec-3606-49fd-89b9-877c40a8bcb5"),
                            EventId = new Guid("e3000000-0000-0000-0000-000000000003"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "B9"
                        },
                        new
                        {
                            Id = new Guid("58ab32bb-4efa-49c0-baba-479363ff01fd"),
                            EventId = new Guid("e3000000-0000-0000-0000-000000000003"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "B10"
                        },
                        new
                        {
                            Id = new Guid("19c7a4ad-7bff-43eb-860c-d8d90411f99d"),
                            EventId = new Guid("e3000000-0000-0000-0000-000000000003"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "C1"
                        },
                        new
                        {
                            Id = new Guid("72233c72-2fcb-4775-865c-096e6fafc941"),
                            EventId = new Guid("e3000000-0000-0000-0000-000000000003"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "C2"
                        },
                        new
                        {
                            Id = new Guid("4e5d3a71-0095-4f98-b9c8-082544a7256e"),
                            EventId = new Guid("e3000000-0000-0000-0000-000000000003"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "C3"
                        },
                        new
                        {
                            Id = new Guid("ee76c451-0477-4e8c-b910-039978739407"),
                            EventId = new Guid("e3000000-0000-0000-0000-000000000003"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "C4"
                        },
                        new
                        {
                            Id = new Guid("35f4e919-cccf-4e33-9275-3db6a4208993"),
                            EventId = new Guid("e3000000-0000-0000-0000-000000000003"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "C5"
                        },
                        new
                        {
                            Id = new Guid("ae21a08a-2433-4f77-a1db-2020733110b3"),
                            EventId = new Guid("e3000000-0000-0000-0000-000000000003"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "C6"
                        },
                        new
                        {
                            Id = new Guid("c9a9ef32-c7a1-4393-9452-57511a9861f4"),
                            EventId = new Guid("e3000000-0000-0000-0000-000000000003"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "C7"
                        },
                        new
                        {
                            Id = new Guid("2f3aca75-25ed-4b11-a1f5-09eca0838636"),
                            EventId = new Guid("e3000000-0000-0000-0000-000000000003"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "C8"
                        },
                        new
                        {
                            Id = new Guid("8d1c26a4-5653-4b32-bb8c-9f52b2812be3"),
                            EventId = new Guid("e3000000-0000-0000-0000-000000000003"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "C9"
                        },
                        new
                        {
                            Id = new Guid("accc419c-410e-4eed-98a2-3bb2ca2c7836"),
                            EventId = new Guid("e3000000-0000-0000-0000-000000000003"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "C10"
                        });
                });

            modelBuilder.Entity("Entities.Models.Reward", b =>
                {
                    b.HasOne("AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Event", b =>
                {
                    b.HasOne("Location", "Location")
                        .WithMany("Events")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Entities.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Entities.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Entities.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Reservation", b =>
                {
                    b.HasOne("Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppUser", "User")
                        .WithMany("Reservations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Ticket", b =>
                {
                    b.HasOne("Event", "Event")
                        .WithMany("Tickets")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Reservation", "Reservation")
                        .WithMany("Tickets")
                        .HasForeignKey("ReservationId");

                    b.Navigation("Event");

                    b.Navigation("Reservation");
                });

            modelBuilder.Entity("AppUser", b =>
                {
                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("Event", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("Location", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("Reservation", b =>
                {
                    b.Navigation("Tickets");
                });
#pragma warning restore 612, 618
        }
    }
}
