// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repository;

#nullable disable

namespace EntrioX.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20251224230509_InitialDatabase")]
    partial class InitialDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UserId");

                    b.Property<string>("BankAccountNumber")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<int>("LoyaltyPoints")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("AppUsers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            BankAccountNumber = "BA392004000012345678",
                            Email = "emin@example.com",
                            FullName = "Emin Džanko",
                            LoyaltyPoints = 0
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            BankAccountNumber = "BA312004000012345679",
                            Email = "john.smith@example.com",
                            FullName = "John Smith",
                            LoyaltyPoints = 0
                        });
                });

            modelBuilder.Entity("Entities.Models.Reward", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("RewardId");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("GrantedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Rewards");
                });

            modelBuilder.Entity("Entities.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "b74ddd14-6340-4840-95c2-db12554843e5",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "b326e934-4c4f-4eb8-94f5-077fc9a8e347",
                            Email = "admin@entriox.com",
                            EmailConfirmed = true,
                            FirstName = "System",
                            LastName = "Administrator",
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@ENTRIOX.COM",
                            NormalizedUserName = "ADMIN@ENTRIOX.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEDheYJgeoNrEwfIX/KjDXWAb+ykCEyqI67aqMRGsNJX30rIYR0CIUu+en+ExMMOPdg==",
                            PhoneNumberConfirmed = false,
                            RefreshTokenExpiryTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SecurityStamp = "c5c3c0b1-d856-48bc-b48a-a685de17b0e4",
                            TwoFactorEnabled = false,
                            UserName = "admin@entriox.com"
                        });
                });

            modelBuilder.Entity("Event", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("EventId");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("EventDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("MinTicketPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e1000000-0000-0000-0000-000000000001"),
                            Capacity = 5000,
                            CreatedAt = new DateTime(2025, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = new Guid("c1000000-0000-0000-0000-000000000001"),
                            Description = "A night of indie rock excellence in the heart of Sarajevo.",
                            EventDate = new DateTime(2026, 6, 15, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationId = new Guid("f1000000-0000-0000-0000-000000000001"),
                            MinTicketPrice = 55.00m,
                            Name = "Arctic Monkeys World Tour"
                        },
                        new
                        {
                            Id = new Guid("e2000000-0000-0000-0000-000000000002"),
                            Capacity = 1200,
                            CreatedAt = new DateTime(2025, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = new Guid("c2000000-0000-0000-0000-000000000002"),
                            Description = "Join the biggest regional gathering of IT experts and innovators.",
                            EventDate = new DateTime(2026, 9, 20, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationId = new Guid("f2000000-0000-0000-0000-000000000002"),
                            MinTicketPrice = 25.50m,
                            Name = "Tech Conference 2026"
                        },
                        new
                        {
                            Id = new Guid("e3000000-0000-0000-0000-000000000003"),
                            Capacity = 800,
                            CreatedAt = new DateTime(2025, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = new Guid("c3000000-0000-0000-0000-000000000003"),
                            Description = "A classic festive performance by the Sarajevo Philharmonic Orchestra.",
                            EventDate = new DateTime(2026, 12, 24, 19, 30, 0, 0, DateTimeKind.Unspecified),
                            LocationId = new Guid("f3000000-0000-0000-0000-000000000003"),
                            MinTicketPrice = 30.00m,
                            Name = "The Nutcracker Ballet"
                        });
                });

            modelBuilder.Entity("Location", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("LocationId");

                    b.Property<string>("Address")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double?>("GeoLatitude")
                        .HasColumnType("float");

                    b.Property<double?>("GeoLongitude")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Locations");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f1000000-0000-0000-0000-000000000001"),
                            Address = "Alipašina bb, Sarajevo",
                            GeoLatitude = 43.866199999999999,
                            GeoLongitude = 18.4131,
                            Name = "Zetra Olympic Hall"
                        },
                        new
                        {
                            Id = new Guid("f2000000-0000-0000-0000-000000000002"),
                            Address = "Terezija bb, Sarajevo",
                            GeoLatitude = 43.856400000000001,
                            GeoLongitude = 18.413,
                            Name = "Skenderija Plateau"
                        },
                        new
                        {
                            Id = new Guid("f3000000-0000-0000-0000-000000000003"),
                            Address = "Obala Kulina bana 9",
                            GeoLatitude = 43.857500000000002,
                            GeoLongitude = 18.4206,
                            Name = "National Theater Sarajevo"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "11363362-56e9-438f-85a4-dc5483dcfe30",
                            Name = "Administrator",
                            NormalizedName = "ADMINISTRATOR"
                        },
                        new
                        {
                            Id = "720daf31-ee16-4555-ab3c-dda08c8c5fb9",
                            Name = "Organizer",
                            NormalizedName = "ORGANIZER"
                        },
                        new
                        {
                            Id = "9ee7f699-298b-4614-9783-addcbff01e6b",
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "b74ddd14-6340-4840-95c2-db12554843e5",
                            RoleId = "11363362-56e9-438f-85a4-dc5483dcfe30"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Reservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ReservationId");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("TotalPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("UserId");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("Ticket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("TicketId");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsReserved")
                        .HasColumnType("bit");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("QRCode")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid?>("ReservationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SeatNumber")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("ReservationId");

                    b.ToTable("Tickets");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c9ed9866-ed01-45d5-9f4c-6f0895fa8c32"),
                            EventId = new Guid("e1000000-0000-0000-0000-000000000001"),
                            IsReserved = false,
                            Price = 55.00m,
                            SeatNumber = "A1"
                        },
                        new
                        {
                            Id = new Guid("17697116-1531-442c-ab0a-bb4ef9d7d4ad"),
                            EventId = new Guid("e1000000-0000-0000-0000-000000000001"),
                            IsReserved = false,
                            Price = 55.00m,
                            SeatNumber = "A2"
                        },
                        new
                        {
                            Id = new Guid("0e8d8266-1c36-4a16-a0a2-63d41c005efc"),
                            EventId = new Guid("e1000000-0000-0000-0000-000000000001"),
                            IsReserved = false,
                            Price = 55.00m,
                            SeatNumber = "A3"
                        },
                        new
                        {
                            Id = new Guid("4d863a8e-109c-4e28-8863-c0ce8772d915"),
                            EventId = new Guid("e1000000-0000-0000-0000-000000000001"),
                            IsReserved = false,
                            Price = 55.00m,
                            SeatNumber = "A4"
                        },
                        new
                        {
                            Id = new Guid("4c4f68ca-bb6a-440c-acf6-bae1c3a11bf9"),
                            EventId = new Guid("e1000000-0000-0000-0000-000000000001"),
                            IsReserved = false,
                            Price = 55.00m,
                            SeatNumber = "A5"
                        },
                        new
                        {
                            Id = new Guid("14cad51c-ffa2-4016-a4fd-8b3c302b065a"),
                            EventId = new Guid("e1000000-0000-0000-0000-000000000001"),
                            IsReserved = false,
                            Price = 55.00m,
                            SeatNumber = "A6"
                        },
                        new
                        {
                            Id = new Guid("98f0c2cc-0432-4400-a5e3-0a0549e3380d"),
                            EventId = new Guid("e1000000-0000-0000-0000-000000000001"),
                            IsReserved = false,
                            Price = 55.00m,
                            SeatNumber = "A7"
                        },
                        new
                        {
                            Id = new Guid("aea451e9-a917-40c4-8ba1-e704f109e034"),
                            EventId = new Guid("e1000000-0000-0000-0000-000000000001"),
                            IsReserved = false,
                            Price = 55.00m,
                            SeatNumber = "A8"
                        },
                        new
                        {
                            Id = new Guid("e4f0aadc-5df7-49aa-805d-1a2d7b23a7df"),
                            EventId = new Guid("e1000000-0000-0000-0000-000000000001"),
                            IsReserved = false,
                            Price = 55.00m,
                            SeatNumber = "A9"
                        },
                        new
                        {
                            Id = new Guid("ba58ba1c-e46a-47fa-9d08-1773ecdfd967"),
                            EventId = new Guid("e1000000-0000-0000-0000-000000000001"),
                            IsReserved = false,
                            Price = 55.00m,
                            SeatNumber = "A10"
                        },
                        new
                        {
                            Id = new Guid("e9f8b455-fc7b-4834-8e2c-2fdda872d238"),
                            EventId = new Guid("e1000000-0000-0000-0000-000000000001"),
                            IsReserved = false,
                            Price = 55.00m,
                            SeatNumber = "B1"
                        },
                        new
                        {
                            Id = new Guid("16658565-fd20-4062-9951-f2fac5eb19f4"),
                            EventId = new Guid("e1000000-0000-0000-0000-000000000001"),
                            IsReserved = false,
                            Price = 55.00m,
                            SeatNumber = "B2"
                        },
                        new
                        {
                            Id = new Guid("f47b1e44-ee4f-487d-be86-f0b7c3b77fda"),
                            EventId = new Guid("e1000000-0000-0000-0000-000000000001"),
                            IsReserved = false,
                            Price = 55.00m,
                            SeatNumber = "B3"
                        },
                        new
                        {
                            Id = new Guid("70c635e0-15d7-4aae-86ee-784a9a36f8f2"),
                            EventId = new Guid("e1000000-0000-0000-0000-000000000001"),
                            IsReserved = false,
                            Price = 55.00m,
                            SeatNumber = "B4"
                        },
                        new
                        {
                            Id = new Guid("d8ab084a-8ce4-4bc6-8d3e-56b788d26ea0"),
                            EventId = new Guid("e1000000-0000-0000-0000-000000000001"),
                            IsReserved = false,
                            Price = 55.00m,
                            SeatNumber = "B5"
                        },
                        new
                        {
                            Id = new Guid("8099725e-1c49-4c60-962c-37623eefac3f"),
                            EventId = new Guid("e1000000-0000-0000-0000-000000000001"),
                            IsReserved = false,
                            Price = 55.00m,
                            SeatNumber = "B6"
                        },
                        new
                        {
                            Id = new Guid("0d74cb19-fd26-4ade-a59a-8ef2cf7f7193"),
                            EventId = new Guid("e1000000-0000-0000-0000-000000000001"),
                            IsReserved = false,
                            Price = 55.00m,
                            SeatNumber = "B7"
                        },
                        new
                        {
                            Id = new Guid("c710936c-53cb-4bb1-9aad-e05e8746ba0d"),
                            EventId = new Guid("e1000000-0000-0000-0000-000000000001"),
                            IsReserved = false,
                            Price = 55.00m,
                            SeatNumber = "B8"
                        },
                        new
                        {
                            Id = new Guid("a7bd7f08-dfdb-427d-b0ef-fc7955a5ad0a"),
                            EventId = new Guid("e1000000-0000-0000-0000-000000000001"),
                            IsReserved = false,
                            Price = 55.00m,
                            SeatNumber = "B9"
                        },
                        new
                        {
                            Id = new Guid("679ef8bc-06ba-4598-a8d6-4db64d6d1673"),
                            EventId = new Guid("e1000000-0000-0000-0000-000000000001"),
                            IsReserved = false,
                            Price = 55.00m,
                            SeatNumber = "B10"
                        },
                        new
                        {
                            Id = new Guid("2e18d142-9bcd-430a-8c6d-bb89c569a8f6"),
                            EventId = new Guid("e1000000-0000-0000-0000-000000000001"),
                            IsReserved = false,
                            Price = 55.00m,
                            SeatNumber = "C1"
                        },
                        new
                        {
                            Id = new Guid("9cba2b40-bd39-47ac-ab34-1db61e8db999"),
                            EventId = new Guid("e1000000-0000-0000-0000-000000000001"),
                            IsReserved = false,
                            Price = 55.00m,
                            SeatNumber = "C2"
                        },
                        new
                        {
                            Id = new Guid("3ee65155-9f0e-4ef9-b31f-d91f65d78fb6"),
                            EventId = new Guid("e1000000-0000-0000-0000-000000000001"),
                            IsReserved = false,
                            Price = 55.00m,
                            SeatNumber = "C3"
                        },
                        new
                        {
                            Id = new Guid("67006265-ece8-4162-963e-1642d31e84ff"),
                            EventId = new Guid("e1000000-0000-0000-0000-000000000001"),
                            IsReserved = false,
                            Price = 55.00m,
                            SeatNumber = "C4"
                        },
                        new
                        {
                            Id = new Guid("f13537b1-de15-4a7e-94c1-abda909c4c1a"),
                            EventId = new Guid("e1000000-0000-0000-0000-000000000001"),
                            IsReserved = false,
                            Price = 55.00m,
                            SeatNumber = "C5"
                        },
                        new
                        {
                            Id = new Guid("4d13b0cc-4d78-4359-ba39-8fbb5cc6fdc2"),
                            EventId = new Guid("e1000000-0000-0000-0000-000000000001"),
                            IsReserved = false,
                            Price = 55.00m,
                            SeatNumber = "C6"
                        },
                        new
                        {
                            Id = new Guid("3ea2fa39-6e0d-4b6b-bb54-f6a14fffa43f"),
                            EventId = new Guid("e1000000-0000-0000-0000-000000000001"),
                            IsReserved = false,
                            Price = 55.00m,
                            SeatNumber = "C7"
                        },
                        new
                        {
                            Id = new Guid("a6127a1a-c5b3-453d-bc87-e09342ef9ac9"),
                            EventId = new Guid("e1000000-0000-0000-0000-000000000001"),
                            IsReserved = false,
                            Price = 55.00m,
                            SeatNumber = "C8"
                        },
                        new
                        {
                            Id = new Guid("442fa437-087d-46b4-a1ea-6fee330d7e49"),
                            EventId = new Guid("e1000000-0000-0000-0000-000000000001"),
                            IsReserved = false,
                            Price = 55.00m,
                            SeatNumber = "C9"
                        },
                        new
                        {
                            Id = new Guid("9db97fa9-d87d-42d3-b187-8e592566a7e4"),
                            EventId = new Guid("e1000000-0000-0000-0000-000000000001"),
                            IsReserved = false,
                            Price = 55.00m,
                            SeatNumber = "C10"
                        },
                        new
                        {
                            Id = new Guid("498d2399-3974-45d7-bd34-538d06a3bb90"),
                            EventId = new Guid("e2000000-0000-0000-0000-000000000002"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "A1"
                        },
                        new
                        {
                            Id = new Guid("47cebf12-2b0c-4117-bed6-35911bdcb90c"),
                            EventId = new Guid("e2000000-0000-0000-0000-000000000002"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "A2"
                        },
                        new
                        {
                            Id = new Guid("b8baf332-2b9d-4f11-ae6a-ca9f8a22d7c3"),
                            EventId = new Guid("e2000000-0000-0000-0000-000000000002"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "A3"
                        },
                        new
                        {
                            Id = new Guid("0fb487da-a88c-4825-a814-c660c87ed7a5"),
                            EventId = new Guid("e2000000-0000-0000-0000-000000000002"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "A4"
                        },
                        new
                        {
                            Id = new Guid("a49c95a0-872d-4fdf-9a5d-f5c262beabeb"),
                            EventId = new Guid("e2000000-0000-0000-0000-000000000002"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "A5"
                        },
                        new
                        {
                            Id = new Guid("4daa23fb-ad16-4c2b-8063-8c41f86fdc45"),
                            EventId = new Guid("e2000000-0000-0000-0000-000000000002"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "A6"
                        },
                        new
                        {
                            Id = new Guid("529602eb-e958-4170-b4b9-6482d0c15be3"),
                            EventId = new Guid("e2000000-0000-0000-0000-000000000002"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "A7"
                        },
                        new
                        {
                            Id = new Guid("c82dade8-d47d-486a-b665-a61226f0cd7b"),
                            EventId = new Guid("e2000000-0000-0000-0000-000000000002"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "A8"
                        },
                        new
                        {
                            Id = new Guid("ace3f070-c7fa-4a40-8668-adf925b05b24"),
                            EventId = new Guid("e2000000-0000-0000-0000-000000000002"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "A9"
                        },
                        new
                        {
                            Id = new Guid("2878e936-ca6b-4523-94c9-75b6d52e0b73"),
                            EventId = new Guid("e2000000-0000-0000-0000-000000000002"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "A10"
                        },
                        new
                        {
                            Id = new Guid("679d4637-b8f8-4d45-ae42-1ba733fa5f70"),
                            EventId = new Guid("e2000000-0000-0000-0000-000000000002"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "B1"
                        },
                        new
                        {
                            Id = new Guid("42a9867d-30ed-45ac-8bf0-07a3f86d6640"),
                            EventId = new Guid("e2000000-0000-0000-0000-000000000002"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "B2"
                        },
                        new
                        {
                            Id = new Guid("85e418b6-b1e5-4a32-9c6b-c1b9a83d2a71"),
                            EventId = new Guid("e2000000-0000-0000-0000-000000000002"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "B3"
                        },
                        new
                        {
                            Id = new Guid("9f579cfb-9d44-405b-87c7-21394400c767"),
                            EventId = new Guid("e2000000-0000-0000-0000-000000000002"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "B4"
                        },
                        new
                        {
                            Id = new Guid("ddf62be9-914e-4a0f-9505-b2f613f50bfd"),
                            EventId = new Guid("e2000000-0000-0000-0000-000000000002"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "B5"
                        },
                        new
                        {
                            Id = new Guid("ebbfb5fe-6b8c-434f-94a0-8531f2f6905a"),
                            EventId = new Guid("e2000000-0000-0000-0000-000000000002"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "B6"
                        },
                        new
                        {
                            Id = new Guid("dee3d191-5481-40b4-ad76-73cdfa095c6d"),
                            EventId = new Guid("e2000000-0000-0000-0000-000000000002"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "B7"
                        },
                        new
                        {
                            Id = new Guid("4bde3763-6530-4c7b-9e29-1701f4d518ca"),
                            EventId = new Guid("e2000000-0000-0000-0000-000000000002"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "B8"
                        },
                        new
                        {
                            Id = new Guid("adb5da2b-1653-4c73-b859-a37d37c5cec9"),
                            EventId = new Guid("e2000000-0000-0000-0000-000000000002"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "B9"
                        },
                        new
                        {
                            Id = new Guid("31a7e58c-874b-4643-8e49-8227e9427d7a"),
                            EventId = new Guid("e2000000-0000-0000-0000-000000000002"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "B10"
                        },
                        new
                        {
                            Id = new Guid("23472e69-45c5-4356-a088-87108b42057c"),
                            EventId = new Guid("e2000000-0000-0000-0000-000000000002"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "C1"
                        },
                        new
                        {
                            Id = new Guid("feca4e4c-ab74-4f71-8c77-cfb8613ab8ac"),
                            EventId = new Guid("e2000000-0000-0000-0000-000000000002"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "C2"
                        },
                        new
                        {
                            Id = new Guid("52fe4be3-9c45-4522-9d7b-4da75340f18d"),
                            EventId = new Guid("e2000000-0000-0000-0000-000000000002"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "C3"
                        },
                        new
                        {
                            Id = new Guid("b53d52de-8691-4329-b7cf-a1d015b31c8c"),
                            EventId = new Guid("e2000000-0000-0000-0000-000000000002"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "C4"
                        },
                        new
                        {
                            Id = new Guid("ce814e94-ab63-463d-a606-6f071a8dcb9d"),
                            EventId = new Guid("e2000000-0000-0000-0000-000000000002"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "C5"
                        },
                        new
                        {
                            Id = new Guid("0eadf084-cd88-4aa1-a57d-769bab6f815f"),
                            EventId = new Guid("e2000000-0000-0000-0000-000000000002"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "C6"
                        },
                        new
                        {
                            Id = new Guid("2e768318-a944-48bf-b5a2-95e329590146"),
                            EventId = new Guid("e2000000-0000-0000-0000-000000000002"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "C7"
                        },
                        new
                        {
                            Id = new Guid("7c19dad1-8f86-46fe-a96d-9c144601baec"),
                            EventId = new Guid("e2000000-0000-0000-0000-000000000002"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "C8"
                        },
                        new
                        {
                            Id = new Guid("7c085bda-5067-4c39-b9f5-029356184254"),
                            EventId = new Guid("e2000000-0000-0000-0000-000000000002"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "C9"
                        },
                        new
                        {
                            Id = new Guid("da38bcaa-16a4-49db-ac32-01b4cddda775"),
                            EventId = new Guid("e2000000-0000-0000-0000-000000000002"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "C10"
                        },
                        new
                        {
                            Id = new Guid("5849d9d3-78d8-4d26-991d-e0d862934820"),
                            EventId = new Guid("e3000000-0000-0000-0000-000000000003"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "A1"
                        },
                        new
                        {
                            Id = new Guid("fe7ef0cc-e6b9-415c-95bc-8ffece272eb0"),
                            EventId = new Guid("e3000000-0000-0000-0000-000000000003"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "A2"
                        },
                        new
                        {
                            Id = new Guid("fb3ca82f-048a-4139-8759-de6c836931a0"),
                            EventId = new Guid("e3000000-0000-0000-0000-000000000003"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "A3"
                        },
                        new
                        {
                            Id = new Guid("6f60a5e1-d2d9-4e2c-8def-4cd6316a5039"),
                            EventId = new Guid("e3000000-0000-0000-0000-000000000003"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "A4"
                        },
                        new
                        {
                            Id = new Guid("5fd4d675-7481-4021-a54c-c5120558b865"),
                            EventId = new Guid("e3000000-0000-0000-0000-000000000003"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "A5"
                        },
                        new
                        {
                            Id = new Guid("e1ddd0d8-be0f-45ff-94eb-ca284ac9ada5"),
                            EventId = new Guid("e3000000-0000-0000-0000-000000000003"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "A6"
                        },
                        new
                        {
                            Id = new Guid("964c59a5-e090-410a-b018-68a5f6946c6a"),
                            EventId = new Guid("e3000000-0000-0000-0000-000000000003"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "A7"
                        },
                        new
                        {
                            Id = new Guid("e1397a0d-9f07-4a68-9f3d-4725361efce4"),
                            EventId = new Guid("e3000000-0000-0000-0000-000000000003"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "A8"
                        },
                        new
                        {
                            Id = new Guid("1691de6a-85ae-408b-9d74-9e3bfb3f8986"),
                            EventId = new Guid("e3000000-0000-0000-0000-000000000003"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "A9"
                        },
                        new
                        {
                            Id = new Guid("3ed71b7e-a70c-4ed5-92c0-9e8abef1ba59"),
                            EventId = new Guid("e3000000-0000-0000-0000-000000000003"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "A10"
                        },
                        new
                        {
                            Id = new Guid("defb9731-b867-4533-bea9-5ddb23ce36dd"),
                            EventId = new Guid("e3000000-0000-0000-0000-000000000003"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "B1"
                        },
                        new
                        {
                            Id = new Guid("ef145492-f8da-428c-ad50-77db65d46571"),
                            EventId = new Guid("e3000000-0000-0000-0000-000000000003"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "B2"
                        },
                        new
                        {
                            Id = new Guid("9093a81f-83db-4b4b-8c2a-036e42e28573"),
                            EventId = new Guid("e3000000-0000-0000-0000-000000000003"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "B3"
                        },
                        new
                        {
                            Id = new Guid("0488044a-3f77-4e72-beaa-79082354b8cb"),
                            EventId = new Guid("e3000000-0000-0000-0000-000000000003"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "B4"
                        },
                        new
                        {
                            Id = new Guid("8de29e7f-665c-424a-ab8d-25858862969e"),
                            EventId = new Guid("e3000000-0000-0000-0000-000000000003"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "B5"
                        },
                        new
                        {
                            Id = new Guid("b8e81f3d-d47c-476d-9e63-90ffa742ef2a"),
                            EventId = new Guid("e3000000-0000-0000-0000-000000000003"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "B6"
                        },
                        new
                        {
                            Id = new Guid("b7066848-fb34-4cc8-aee3-54656ff23a38"),
                            EventId = new Guid("e3000000-0000-0000-0000-000000000003"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "B7"
                        },
                        new
                        {
                            Id = new Guid("5c7aabea-d063-4955-a33d-35b67aa44e2f"),
                            EventId = new Guid("e3000000-0000-0000-0000-000000000003"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "B8"
                        },
                        new
                        {
                            Id = new Guid("e06fd6a9-caa4-47a3-8c9c-1c0577078337"),
                            EventId = new Guid("e3000000-0000-0000-0000-000000000003"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "B9"
                        },
                        new
                        {
                            Id = new Guid("f0712d97-05b9-4921-85f6-7f218c049f58"),
                            EventId = new Guid("e3000000-0000-0000-0000-000000000003"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "B10"
                        },
                        new
                        {
                            Id = new Guid("e1130ff6-335e-4fdc-bae6-9d4d4f2d8b51"),
                            EventId = new Guid("e3000000-0000-0000-0000-000000000003"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "C1"
                        },
                        new
                        {
                            Id = new Guid("ca5de8c3-8485-444f-8af9-a5001ea06f46"),
                            EventId = new Guid("e3000000-0000-0000-0000-000000000003"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "C2"
                        },
                        new
                        {
                            Id = new Guid("77a09b32-8181-411e-ab6b-62a50758be7a"),
                            EventId = new Guid("e3000000-0000-0000-0000-000000000003"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "C3"
                        },
                        new
                        {
                            Id = new Guid("d7211352-f20e-47f2-8942-3e02603d3c84"),
                            EventId = new Guid("e3000000-0000-0000-0000-000000000003"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "C4"
                        },
                        new
                        {
                            Id = new Guid("eff246cc-f9f4-4fa8-a80f-0a4c63e1ff8b"),
                            EventId = new Guid("e3000000-0000-0000-0000-000000000003"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "C5"
                        },
                        new
                        {
                            Id = new Guid("7ea58541-00b4-4ed0-9170-c27d922df865"),
                            EventId = new Guid("e3000000-0000-0000-0000-000000000003"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "C6"
                        },
                        new
                        {
                            Id = new Guid("b5c4e261-a747-482c-88b3-334bf8c17108"),
                            EventId = new Guid("e3000000-0000-0000-0000-000000000003"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "C7"
                        },
                        new
                        {
                            Id = new Guid("330eb0ef-a92f-4974-8878-e86dddb801e3"),
                            EventId = new Guid("e3000000-0000-0000-0000-000000000003"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "C8"
                        },
                        new
                        {
                            Id = new Guid("abc3c23e-f26e-47c2-98ce-aa53cf55e06e"),
                            EventId = new Guid("e3000000-0000-0000-0000-000000000003"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "C9"
                        },
                        new
                        {
                            Id = new Guid("c6e63764-8358-4c13-adb8-412b1e8d6fd1"),
                            EventId = new Guid("e3000000-0000-0000-0000-000000000003"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "C10"
                        });
                });

            modelBuilder.Entity("Entities.Models.Reward", b =>
                {
                    b.HasOne("AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Event", b =>
                {
                    b.HasOne("Location", "Location")
                        .WithMany("Events")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Entities.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Entities.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Entities.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Reservation", b =>
                {
                    b.HasOne("Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppUser", "User")
                        .WithMany("Reservations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Ticket", b =>
                {
                    b.HasOne("Event", "Event")
                        .WithMany("Tickets")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Reservation", "Reservation")
                        .WithMany("Tickets")
                        .HasForeignKey("ReservationId");

                    b.Navigation("Event");

                    b.Navigation("Reservation");
                });

            modelBuilder.Entity("AppUser", b =>
                {
                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("Event", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("Location", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("Reservation", b =>
                {
                    b.Navigation("Tickets");
                });
#pragma warning restore 612, 618
        }
    }
}
