// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repository;

#nullable disable

namespace EntrioX.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20251224201326_AddCreatorAndCapacity")]
    partial class AddCreatorAndCapacity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UserId");

                    b.Property<string>("BankAccountNumber")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.ToTable("AppUsers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            BankAccountNumber = "BA392004000012345678",
                            Email = "emin@example.com",
                            FullName = "Emin Džanko"
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            Email = "john.smith@example.com",
                            FullName = "John Smith"
                        });
                });

            modelBuilder.Entity("Entities.Models.Reward", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("RewardId");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("GrantedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Rewards");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Description = "Early supporter reward",
                            GrantedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "/images/rewards/supporter.png",
                            UserId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa")
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Description = "Top buyer of the month",
                            GrantedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "/images/rewards/topbuyer.png",
                            UserId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb")
                        });
                });

            modelBuilder.Entity("Entities.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Event", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("EventId");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("EventDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("MinTicketPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e1000000-0000-0000-0000-000000000001"),
                            Capacity = 5000,
                            CreatedAt = new DateTime(2025, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = new Guid("c1000000-0000-0000-0000-000000000001"),
                            Description = "A night of indie rock excellence in the heart of Sarajevo.",
                            EventDate = new DateTime(2026, 6, 15, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationId = new Guid("f1000000-0000-0000-0000-000000000001"),
                            MinTicketPrice = 0m,
                            Name = "Arctic Monkeys World Tour"
                        },
                        new
                        {
                            Id = new Guid("e2000000-0000-0000-0000-000000000002"),
                            Capacity = 1200,
                            CreatedAt = new DateTime(2025, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = new Guid("c2000000-0000-0000-0000-000000000002"),
                            Description = "Join the biggest regional gathering of IT experts and innovators.",
                            EventDate = new DateTime(2026, 9, 20, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationId = new Guid("f2000000-0000-0000-0000-000000000002"),
                            MinTicketPrice = 0m,
                            Name = "Tech Conference 2026"
                        },
                        new
                        {
                            Id = new Guid("e3000000-0000-0000-0000-000000000003"),
                            Capacity = 800,
                            CreatedAt = new DateTime(2025, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = new Guid("c3000000-0000-0000-0000-000000000003"),
                            Description = "A classic festive performance by the Sarajevo Philharmonic Orchestra.",
                            EventDate = new DateTime(2026, 12, 24, 19, 30, 0, 0, DateTimeKind.Unspecified),
                            LocationId = new Guid("f3000000-0000-0000-0000-000000000003"),
                            MinTicketPrice = 0m,
                            Name = "The Nutcracker Ballet"
                        });
                });

            modelBuilder.Entity("Location", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("LocationId");

                    b.Property<string>("Address")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double?>("GeoLatitude")
                        .HasColumnType("float");

                    b.Property<double?>("GeoLongitude")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Locations");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f1000000-0000-0000-0000-000000000001"),
                            Address = "Alipašina bb, Sarajevo",
                            GeoLatitude = 43.866199999999999,
                            GeoLongitude = 18.4131,
                            Name = "Zetra Olympic Hall"
                        },
                        new
                        {
                            Id = new Guid("f2000000-0000-0000-0000-000000000002"),
                            Address = "Terezija bb, Sarajevo",
                            GeoLatitude = 43.856400000000001,
                            GeoLongitude = 18.413,
                            Name = "Skenderija Plateau"
                        },
                        new
                        {
                            Id = new Guid("f3000000-0000-0000-0000-000000000003"),
                            Address = "Obala Kulina bana 9",
                            GeoLatitude = 43.857500000000002,
                            GeoLongitude = 18.4206,
                            Name = "National Theater Sarajevo"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Reservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ReservationId");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("TotalPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("UserId");

                    b.ToTable("Reservations");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d1000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EventId = new Guid("e1000000-0000-0000-0000-000000000001"),
                            TotalPrice = 50.00m,
                            UserId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa")
                        });
                });

            modelBuilder.Entity("Ticket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("TicketId");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsReserved")
                        .HasColumnType("bit");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("QRCode")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid?>("ReservationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SeatNumber")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("ReservationId");

                    b.ToTable("Tickets");

                    b.HasData(
                        new
                        {
                            Id = new Guid("af16de97-711a-4a7c-bb64-36f6f6b12680"),
                            EventId = new Guid("e1000000-0000-0000-0000-000000000001"),
                            IsReserved = false,
                            Price = 55.00m,
                            SeatNumber = "A1"
                        },
                        new
                        {
                            Id = new Guid("bb216c13-b378-4012-9b4e-10fb2f2e1440"),
                            EventId = new Guid("e1000000-0000-0000-0000-000000000001"),
                            IsReserved = false,
                            Price = 55.00m,
                            SeatNumber = "A2"
                        },
                        new
                        {
                            Id = new Guid("793534aa-a722-4b5f-a268-9447fa71e2e1"),
                            EventId = new Guid("e1000000-0000-0000-0000-000000000001"),
                            IsReserved = false,
                            Price = 55.00m,
                            SeatNumber = "A3"
                        },
                        new
                        {
                            Id = new Guid("8fb7f081-6358-4faa-8c2a-dc5ac72314b2"),
                            EventId = new Guid("e1000000-0000-0000-0000-000000000001"),
                            IsReserved = false,
                            Price = 55.00m,
                            SeatNumber = "A4"
                        },
                        new
                        {
                            Id = new Guid("10749759-a0f9-4135-aa40-d315099aad8d"),
                            EventId = new Guid("e1000000-0000-0000-0000-000000000001"),
                            IsReserved = false,
                            Price = 55.00m,
                            SeatNumber = "A5"
                        },
                        new
                        {
                            Id = new Guid("2a11bbe2-3c78-414c-88d0-55fcaaf19af5"),
                            EventId = new Guid("e1000000-0000-0000-0000-000000000001"),
                            IsReserved = false,
                            Price = 55.00m,
                            SeatNumber = "A6"
                        },
                        new
                        {
                            Id = new Guid("10ed45db-24ad-4a0f-9a67-b70e900d117e"),
                            EventId = new Guid("e1000000-0000-0000-0000-000000000001"),
                            IsReserved = false,
                            Price = 55.00m,
                            SeatNumber = "A7"
                        },
                        new
                        {
                            Id = new Guid("9e6f9ac2-b01a-4a50-afc2-09ba64771cf2"),
                            EventId = new Guid("e1000000-0000-0000-0000-000000000001"),
                            IsReserved = false,
                            Price = 55.00m,
                            SeatNumber = "A8"
                        },
                        new
                        {
                            Id = new Guid("4afc339d-fa3b-4731-ad11-e8fcd320f172"),
                            EventId = new Guid("e1000000-0000-0000-0000-000000000001"),
                            IsReserved = false,
                            Price = 55.00m,
                            SeatNumber = "A9"
                        },
                        new
                        {
                            Id = new Guid("ea9a7ed1-390f-4f59-ad16-0d1b9d804438"),
                            EventId = new Guid("e1000000-0000-0000-0000-000000000001"),
                            IsReserved = false,
                            Price = 55.00m,
                            SeatNumber = "A10"
                        },
                        new
                        {
                            Id = new Guid("0ed98450-0014-427c-953d-2d3b4b1faeb4"),
                            EventId = new Guid("e1000000-0000-0000-0000-000000000001"),
                            IsReserved = false,
                            Price = 55.00m,
                            SeatNumber = "B1"
                        },
                        new
                        {
                            Id = new Guid("37c5fb53-8b83-4f3b-9fe5-850d33df5acb"),
                            EventId = new Guid("e1000000-0000-0000-0000-000000000001"),
                            IsReserved = false,
                            Price = 55.00m,
                            SeatNumber = "B2"
                        },
                        new
                        {
                            Id = new Guid("003ae424-9927-4661-be95-929a67f6f10a"),
                            EventId = new Guid("e1000000-0000-0000-0000-000000000001"),
                            IsReserved = false,
                            Price = 55.00m,
                            SeatNumber = "B3"
                        },
                        new
                        {
                            Id = new Guid("ed63baab-f252-4ada-8c44-dc136bbe0f94"),
                            EventId = new Guid("e1000000-0000-0000-0000-000000000001"),
                            IsReserved = false,
                            Price = 55.00m,
                            SeatNumber = "B4"
                        },
                        new
                        {
                            Id = new Guid("f3a26f6f-3452-4464-82b6-b8b6d96ba25c"),
                            EventId = new Guid("e1000000-0000-0000-0000-000000000001"),
                            IsReserved = false,
                            Price = 55.00m,
                            SeatNumber = "B5"
                        },
                        new
                        {
                            Id = new Guid("0cef4d27-1dad-46d1-a516-1471db4ed7ed"),
                            EventId = new Guid("e1000000-0000-0000-0000-000000000001"),
                            IsReserved = false,
                            Price = 55.00m,
                            SeatNumber = "B6"
                        },
                        new
                        {
                            Id = new Guid("4d7b2420-89a2-43b5-95bd-971059688839"),
                            EventId = new Guid("e1000000-0000-0000-0000-000000000001"),
                            IsReserved = false,
                            Price = 55.00m,
                            SeatNumber = "B7"
                        },
                        new
                        {
                            Id = new Guid("ed68812d-8fb0-45b0-9871-1b8d5ab02dc1"),
                            EventId = new Guid("e1000000-0000-0000-0000-000000000001"),
                            IsReserved = false,
                            Price = 55.00m,
                            SeatNumber = "B8"
                        },
                        new
                        {
                            Id = new Guid("a8647615-d589-446a-a98d-a92fa9c46d4e"),
                            EventId = new Guid("e1000000-0000-0000-0000-000000000001"),
                            IsReserved = false,
                            Price = 55.00m,
                            SeatNumber = "B9"
                        },
                        new
                        {
                            Id = new Guid("c78af718-ca28-45dd-a8db-b39c1041d908"),
                            EventId = new Guid("e1000000-0000-0000-0000-000000000001"),
                            IsReserved = false,
                            Price = 55.00m,
                            SeatNumber = "B10"
                        },
                        new
                        {
                            Id = new Guid("cc0876a3-e379-4ed1-b05f-32917ec47ead"),
                            EventId = new Guid("e1000000-0000-0000-0000-000000000001"),
                            IsReserved = false,
                            Price = 55.00m,
                            SeatNumber = "C1"
                        },
                        new
                        {
                            Id = new Guid("12405edb-6d6c-49c9-b503-c9b62de79c3c"),
                            EventId = new Guid("e1000000-0000-0000-0000-000000000001"),
                            IsReserved = false,
                            Price = 55.00m,
                            SeatNumber = "C2"
                        },
                        new
                        {
                            Id = new Guid("a1341ac7-d2ae-458c-9263-af97d317222f"),
                            EventId = new Guid("e1000000-0000-0000-0000-000000000001"),
                            IsReserved = false,
                            Price = 55.00m,
                            SeatNumber = "C3"
                        },
                        new
                        {
                            Id = new Guid("63f5c55a-4be4-4ba6-bc46-cbfca5002bd6"),
                            EventId = new Guid("e1000000-0000-0000-0000-000000000001"),
                            IsReserved = false,
                            Price = 55.00m,
                            SeatNumber = "C4"
                        },
                        new
                        {
                            Id = new Guid("1141c161-3d82-4807-af68-2bff93251815"),
                            EventId = new Guid("e1000000-0000-0000-0000-000000000001"),
                            IsReserved = false,
                            Price = 55.00m,
                            SeatNumber = "C5"
                        },
                        new
                        {
                            Id = new Guid("402e852b-c918-4bd7-8394-dd1be3098086"),
                            EventId = new Guid("e1000000-0000-0000-0000-000000000001"),
                            IsReserved = false,
                            Price = 55.00m,
                            SeatNumber = "C6"
                        },
                        new
                        {
                            Id = new Guid("ce9bfcda-1e31-4919-b44a-75237d13cef9"),
                            EventId = new Guid("e1000000-0000-0000-0000-000000000001"),
                            IsReserved = false,
                            Price = 55.00m,
                            SeatNumber = "C7"
                        },
                        new
                        {
                            Id = new Guid("d373d582-ff09-4510-a1db-e70f5c368d0f"),
                            EventId = new Guid("e1000000-0000-0000-0000-000000000001"),
                            IsReserved = false,
                            Price = 55.00m,
                            SeatNumber = "C8"
                        },
                        new
                        {
                            Id = new Guid("927ccf22-a583-4694-ad6e-9a7781cb66fc"),
                            EventId = new Guid("e1000000-0000-0000-0000-000000000001"),
                            IsReserved = false,
                            Price = 55.00m,
                            SeatNumber = "C9"
                        },
                        new
                        {
                            Id = new Guid("9c11cce7-3f02-407c-a667-60415fec96e2"),
                            EventId = new Guid("e1000000-0000-0000-0000-000000000001"),
                            IsReserved = false,
                            Price = 55.00m,
                            SeatNumber = "C10"
                        },
                        new
                        {
                            Id = new Guid("dbede25a-5bce-4759-ab65-82e135ceac99"),
                            EventId = new Guid("e2000000-0000-0000-0000-000000000002"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "A1"
                        },
                        new
                        {
                            Id = new Guid("99b15123-62a0-4422-810c-d6e32d25d4cb"),
                            EventId = new Guid("e2000000-0000-0000-0000-000000000002"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "A2"
                        },
                        new
                        {
                            Id = new Guid("d52bedae-6b08-4043-8420-585ac06500f3"),
                            EventId = new Guid("e2000000-0000-0000-0000-000000000002"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "A3"
                        },
                        new
                        {
                            Id = new Guid("16141baf-e5cf-473f-b44e-23eda8960ab0"),
                            EventId = new Guid("e2000000-0000-0000-0000-000000000002"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "A4"
                        },
                        new
                        {
                            Id = new Guid("dd6ba341-d3ab-4287-b379-1f1dbbe4c9bd"),
                            EventId = new Guid("e2000000-0000-0000-0000-000000000002"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "A5"
                        },
                        new
                        {
                            Id = new Guid("b19e58ba-1cbc-4a6c-b737-5eac308b40f2"),
                            EventId = new Guid("e2000000-0000-0000-0000-000000000002"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "A6"
                        },
                        new
                        {
                            Id = new Guid("f6e02eb8-d181-4c2f-80c7-5f9260e8f219"),
                            EventId = new Guid("e2000000-0000-0000-0000-000000000002"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "A7"
                        },
                        new
                        {
                            Id = new Guid("2c264e8e-2036-4d0f-af1d-0c3f0113de46"),
                            EventId = new Guid("e2000000-0000-0000-0000-000000000002"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "A8"
                        },
                        new
                        {
                            Id = new Guid("87325c11-f7f3-49cf-94db-f06f4d873bf9"),
                            EventId = new Guid("e2000000-0000-0000-0000-000000000002"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "A9"
                        },
                        new
                        {
                            Id = new Guid("9074351b-a8ac-4c40-bd6f-ec92003c2e5d"),
                            EventId = new Guid("e2000000-0000-0000-0000-000000000002"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "A10"
                        },
                        new
                        {
                            Id = new Guid("a3861c2b-826c-4bda-8b4f-4ea1331ddd6c"),
                            EventId = new Guid("e2000000-0000-0000-0000-000000000002"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "B1"
                        },
                        new
                        {
                            Id = new Guid("17b20926-eac9-47c7-9493-43d2f2596b81"),
                            EventId = new Guid("e2000000-0000-0000-0000-000000000002"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "B2"
                        },
                        new
                        {
                            Id = new Guid("88ef4547-5197-4d51-b552-23c551148b5c"),
                            EventId = new Guid("e2000000-0000-0000-0000-000000000002"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "B3"
                        },
                        new
                        {
                            Id = new Guid("a6a18020-91d9-460b-b99a-d6e4035c997d"),
                            EventId = new Guid("e2000000-0000-0000-0000-000000000002"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "B4"
                        },
                        new
                        {
                            Id = new Guid("4c2d01d7-cf9d-4987-b64a-56f447cdd96c"),
                            EventId = new Guid("e2000000-0000-0000-0000-000000000002"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "B5"
                        },
                        new
                        {
                            Id = new Guid("e42511af-4fe8-424f-98c5-3639dc1bb05e"),
                            EventId = new Guid("e2000000-0000-0000-0000-000000000002"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "B6"
                        },
                        new
                        {
                            Id = new Guid("7384f4e2-265b-4052-8764-a62fc1be8e4b"),
                            EventId = new Guid("e2000000-0000-0000-0000-000000000002"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "B7"
                        },
                        new
                        {
                            Id = new Guid("5b455ce6-3fee-4346-9135-4f26b707c4d6"),
                            EventId = new Guid("e2000000-0000-0000-0000-000000000002"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "B8"
                        },
                        new
                        {
                            Id = new Guid("9a2250ca-571d-4680-9aaa-1b3627be5cdc"),
                            EventId = new Guid("e2000000-0000-0000-0000-000000000002"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "B9"
                        },
                        new
                        {
                            Id = new Guid("56381e11-45ad-4cbf-bd62-04bbecf58894"),
                            EventId = new Guid("e2000000-0000-0000-0000-000000000002"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "B10"
                        },
                        new
                        {
                            Id = new Guid("2395d1f5-5f26-4c56-93f2-250a70d31e81"),
                            EventId = new Guid("e2000000-0000-0000-0000-000000000002"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "C1"
                        },
                        new
                        {
                            Id = new Guid("9acd0d4e-8f20-4db2-be18-9c85c4416189"),
                            EventId = new Guid("e2000000-0000-0000-0000-000000000002"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "C2"
                        },
                        new
                        {
                            Id = new Guid("7326a9e9-9daf-4420-bd36-2dfe0093ea1a"),
                            EventId = new Guid("e2000000-0000-0000-0000-000000000002"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "C3"
                        },
                        new
                        {
                            Id = new Guid("423fb7a6-dbf0-4ccc-a599-eebd85842890"),
                            EventId = new Guid("e2000000-0000-0000-0000-000000000002"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "C4"
                        },
                        new
                        {
                            Id = new Guid("4e4a7020-a66e-4b0d-942d-4ce081fa55b6"),
                            EventId = new Guid("e2000000-0000-0000-0000-000000000002"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "C5"
                        },
                        new
                        {
                            Id = new Guid("b8c99849-387c-4495-8033-19a17ba563be"),
                            EventId = new Guid("e2000000-0000-0000-0000-000000000002"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "C6"
                        },
                        new
                        {
                            Id = new Guid("77e1d8bc-8b3a-45bf-8629-0be24af713b7"),
                            EventId = new Guid("e2000000-0000-0000-0000-000000000002"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "C7"
                        },
                        new
                        {
                            Id = new Guid("2467ad39-470c-4f7d-b02c-d75e2ba64de4"),
                            EventId = new Guid("e2000000-0000-0000-0000-000000000002"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "C8"
                        },
                        new
                        {
                            Id = new Guid("9f4ef672-f7ef-45bc-b368-4d7625793ff9"),
                            EventId = new Guid("e2000000-0000-0000-0000-000000000002"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "C9"
                        },
                        new
                        {
                            Id = new Guid("7029fe56-3691-487d-a612-db7f8050dc33"),
                            EventId = new Guid("e2000000-0000-0000-0000-000000000002"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "C10"
                        },
                        new
                        {
                            Id = new Guid("e6189d3d-28d9-4776-abd1-f56c730ea5d8"),
                            EventId = new Guid("e3000000-0000-0000-0000-000000000003"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "A1"
                        },
                        new
                        {
                            Id = new Guid("86d7b8c8-15b3-4150-a63f-ba88fbfc2398"),
                            EventId = new Guid("e3000000-0000-0000-0000-000000000003"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "A2"
                        },
                        new
                        {
                            Id = new Guid("7c9c8578-dca2-4cad-93e9-cb8eeb536399"),
                            EventId = new Guid("e3000000-0000-0000-0000-000000000003"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "A3"
                        },
                        new
                        {
                            Id = new Guid("6b7023b5-9cb6-4de0-8681-564566ab70c2"),
                            EventId = new Guid("e3000000-0000-0000-0000-000000000003"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "A4"
                        },
                        new
                        {
                            Id = new Guid("373534b7-5c5c-4cfb-a093-f74c61ca8194"),
                            EventId = new Guid("e3000000-0000-0000-0000-000000000003"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "A5"
                        },
                        new
                        {
                            Id = new Guid("1ab55653-ef27-4dc5-971a-df420f13eef5"),
                            EventId = new Guid("e3000000-0000-0000-0000-000000000003"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "A6"
                        },
                        new
                        {
                            Id = new Guid("0749bc3a-86c0-4756-a145-c48970a3f629"),
                            EventId = new Guid("e3000000-0000-0000-0000-000000000003"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "A7"
                        },
                        new
                        {
                            Id = new Guid("77d3dd2b-fee8-4aaf-a6da-2858e8fe7ad8"),
                            EventId = new Guid("e3000000-0000-0000-0000-000000000003"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "A8"
                        },
                        new
                        {
                            Id = new Guid("5d7ea9b5-41c1-4e5f-8770-d13aa2f4577a"),
                            EventId = new Guid("e3000000-0000-0000-0000-000000000003"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "A9"
                        },
                        new
                        {
                            Id = new Guid("afc9f5d4-752d-4412-902e-e8f577b92357"),
                            EventId = new Guid("e3000000-0000-0000-0000-000000000003"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "A10"
                        },
                        new
                        {
                            Id = new Guid("0074c134-e219-4135-a4cb-1224a437084f"),
                            EventId = new Guid("e3000000-0000-0000-0000-000000000003"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "B1"
                        },
                        new
                        {
                            Id = new Guid("96e838ce-1866-4d2d-b625-b3916a59cfba"),
                            EventId = new Guid("e3000000-0000-0000-0000-000000000003"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "B2"
                        },
                        new
                        {
                            Id = new Guid("eabecfe4-388d-4c79-9539-eee2871cf615"),
                            EventId = new Guid("e3000000-0000-0000-0000-000000000003"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "B3"
                        },
                        new
                        {
                            Id = new Guid("0b6caa6b-4c43-4ad0-9966-557920a983d9"),
                            EventId = new Guid("e3000000-0000-0000-0000-000000000003"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "B4"
                        },
                        new
                        {
                            Id = new Guid("579ef141-45a8-4d7b-8a98-feccf69fee3b"),
                            EventId = new Guid("e3000000-0000-0000-0000-000000000003"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "B5"
                        },
                        new
                        {
                            Id = new Guid("9139b7f4-0d50-4ea6-8bcf-3c6e1e2e18b7"),
                            EventId = new Guid("e3000000-0000-0000-0000-000000000003"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "B6"
                        },
                        new
                        {
                            Id = new Guid("e01f4a14-e1e5-4d08-9f8c-d66df449cfd5"),
                            EventId = new Guid("e3000000-0000-0000-0000-000000000003"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "B7"
                        },
                        new
                        {
                            Id = new Guid("80dc8746-c93b-4329-a043-2dc3a6884590"),
                            EventId = new Guid("e3000000-0000-0000-0000-000000000003"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "B8"
                        },
                        new
                        {
                            Id = new Guid("8532c985-fdc6-40a7-88de-988aa26cfb70"),
                            EventId = new Guid("e3000000-0000-0000-0000-000000000003"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "B9"
                        },
                        new
                        {
                            Id = new Guid("c34046fa-6c78-40e1-b752-37a32805638d"),
                            EventId = new Guid("e3000000-0000-0000-0000-000000000003"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "B10"
                        },
                        new
                        {
                            Id = new Guid("83fad28b-3585-43b9-bfd3-c83c065b93e8"),
                            EventId = new Guid("e3000000-0000-0000-0000-000000000003"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "C1"
                        },
                        new
                        {
                            Id = new Guid("26e7abf2-1169-4195-9e66-0d1bff76054a"),
                            EventId = new Guid("e3000000-0000-0000-0000-000000000003"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "C2"
                        },
                        new
                        {
                            Id = new Guid("25a40867-4210-47e5-8884-0f1e3deefcec"),
                            EventId = new Guid("e3000000-0000-0000-0000-000000000003"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "C3"
                        },
                        new
                        {
                            Id = new Guid("447ff861-0229-4664-aa6c-a51a3c8b78dc"),
                            EventId = new Guid("e3000000-0000-0000-0000-000000000003"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "C4"
                        },
                        new
                        {
                            Id = new Guid("afa08559-03fc-412a-a654-6108487e4ed4"),
                            EventId = new Guid("e3000000-0000-0000-0000-000000000003"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "C5"
                        },
                        new
                        {
                            Id = new Guid("e88a2a3e-a8af-4751-873d-8ba67b942bfc"),
                            EventId = new Guid("e3000000-0000-0000-0000-000000000003"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "C6"
                        },
                        new
                        {
                            Id = new Guid("ef8389f2-4d2a-4193-be12-bb5022912631"),
                            EventId = new Guid("e3000000-0000-0000-0000-000000000003"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "C7"
                        },
                        new
                        {
                            Id = new Guid("761b776b-fe78-43ac-a726-5343ced4a57e"),
                            EventId = new Guid("e3000000-0000-0000-0000-000000000003"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "C8"
                        },
                        new
                        {
                            Id = new Guid("81915b7c-2111-48d7-a1ab-fb59170d8ddc"),
                            EventId = new Guid("e3000000-0000-0000-0000-000000000003"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "C9"
                        },
                        new
                        {
                            Id = new Guid("f09a66c3-d153-4e0a-9db3-dd4a5e7c8fc2"),
                            EventId = new Guid("e3000000-0000-0000-0000-000000000003"),
                            IsReserved = false,
                            Price = 25.50m,
                            SeatNumber = "C10"
                        });
                });

            modelBuilder.Entity("Entities.Models.Reward", b =>
                {
                    b.HasOne("AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Event", b =>
                {
                    b.HasOne("Location", "Location")
                        .WithMany("Events")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Entities.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Entities.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Entities.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Reservation", b =>
                {
                    b.HasOne("Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppUser", "User")
                        .WithMany("Reservations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Ticket", b =>
                {
                    b.HasOne("Event", "Event")
                        .WithMany("Tickets")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Reservation", "Reservation")
                        .WithMany("Tickets")
                        .HasForeignKey("ReservationId");

                    b.Navigation("Event");

                    b.Navigation("Reservation");
                });

            modelBuilder.Entity("AppUser", b =>
                {
                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("Event", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("Location", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("Reservation", b =>
                {
                    b.Navigation("Tickets");
                });
#pragma warning restore 612, 618
        }
    }
}
